# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.television import TELEVISION  # noqa: F401,E501
from swagger_server import util


class AllOfDiccionarioDatosTelevision(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, plan: int=None):  # noqa: E501
        """AllOfDiccionarioDatosTelevision - a model defined in Swagger

        :param plan: The plan of this AllOfDiccionarioDatosTelevision.  # noqa: E501
        :type plan: int
        """
        self.swagger_types = {
            'plan': int
        }

        self.attribute_map = {
            'plan': 'Plan'
        }
        self._plan = plan

    @classmethod
    def from_dict(cls, dikt) -> 'AllOfDiccionarioDatosTelevision':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The AllOfDiccionarioDatosTelevision of this AllOfDiccionarioDatosTelevision.  # noqa: E501
        :rtype: AllOfDiccionarioDatosTelevision
        """
        return util.deserialize_model(dikt, cls)

    @property
    def plan(self) -> int:
        """Gets the plan of this AllOfDiccionarioDatosTelevision.


        :return: The plan of this AllOfDiccionarioDatosTelevision.
        :rtype: int
        """
        return self._plan

    @plan.setter
    def plan(self, plan: int):
        """Sets the plan of this AllOfDiccionarioDatosTelevision.


        :param plan: The plan of this AllOfDiccionarioDatosTelevision.
        :type plan: int
        """
        if plan is None:
            raise ValueError("Invalid value for `plan`, must not be `None`")  # noqa: E501

        self._plan = plan
