# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.telefonia import TELEFONIA  # noqa: F401,E501
from swagger_server import util


class AllOfDiccionarioDatosTelefonia(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, plan: int=None):  # noqa: E501
        """AllOfDiccionarioDatosTelefonia - a model defined in Swagger

        :param plan: The plan of this AllOfDiccionarioDatosTelefonia.  # noqa: E501
        :type plan: int
        """
        self.swagger_types = {
            'plan': int
        }

        self.attribute_map = {
            'plan': 'Plan'
        }
        self._plan = plan

    @classmethod
    def from_dict(cls, dikt) -> 'AllOfDiccionarioDatosTelefonia':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The AllOfDiccionarioDatosTelefonia of this AllOfDiccionarioDatosTelefonia.  # noqa: E501
        :rtype: AllOfDiccionarioDatosTelefonia
        """
        return util.deserialize_model(dikt, cls)

    @property
    def plan(self) -> int:
        """Gets the plan of this AllOfDiccionarioDatosTelefonia.


        :return: The plan of this AllOfDiccionarioDatosTelefonia.
        :rtype: int
        """
        return self._plan

    @plan.setter
    def plan(self, plan: int):
        """Sets the plan of this AllOfDiccionarioDatosTelefonia.


        :param plan: The plan of this AllOfDiccionarioDatosTelefonia.
        :type plan: int
        """
        if plan is None:
            raise ValueError("Invalid value for `plan`, must not be `None`")  # noqa: E501

        self._plan = plan
