# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class RequestGetOfertas(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, channel: str=None, type: str=None, stype: str=None, external_transaction_id: str=None):  # noqa: E501
        """RequestGetOfertas - a model defined in Swagger

        :param channel: The channel of this RequestGetOfertas.  # noqa: E501
        :type channel: str
        :param type: The type of this RequestGetOfertas.  # noqa: E501
        :type type: str
        :param stype: The stype of this RequestGetOfertas.  # noqa: E501
        :type stype: str
        :param external_transaction_id: The external_transaction_id of this RequestGetOfertas.  # noqa: E501
        :type external_transaction_id: str
        """
        self.swagger_types = {
            'channel': str,
            'type': str,
            'stype': str,
            'external_transaction_id': str
        }

        self.attribute_map = {
            'channel': 'channel',
            'type': 'type',
            'stype': 'stype',
            'external_transaction_id': 'externalTransactionId'
        }
        self._channel = channel
        self._type = type
        self._stype = stype
        self._external_transaction_id = external_transaction_id

    @classmethod
    def from_dict(cls, dikt) -> 'RequestGetOfertas':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The RequestGetOfertas of this RequestGetOfertas.  # noqa: E501
        :rtype: RequestGetOfertas
        """
        return util.deserialize_model(dikt, cls)

    @property
    def channel(self) -> str:
        """Gets the channel of this RequestGetOfertas.


        :return: The channel of this RequestGetOfertas.
        :rtype: str
        """
        return self._channel

    @channel.setter
    def channel(self, channel: str):
        """Sets the channel of this RequestGetOfertas.


        :param channel: The channel of this RequestGetOfertas.
        :type channel: str
        """
        if channel is None:
            raise ValueError("Invalid value for `channel`, must not be `None`")  # noqa: E501

        self._channel = channel

    @property
    def type(self) -> str:
        """Gets the type of this RequestGetOfertas.


        :return: The type of this RequestGetOfertas.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type: str):
        """Sets the type of this RequestGetOfertas.


        :param type: The type of this RequestGetOfertas.
        :type type: str
        """
        if type is None:
            raise ValueError("Invalid value for `type`, must not be `None`")  # noqa: E501

        self._type = type

    @property
    def stype(self) -> str:
        """Gets the stype of this RequestGetOfertas.


        :return: The stype of this RequestGetOfertas.
        :rtype: str
        """
        return self._stype

    @stype.setter
    def stype(self, stype: str):
        """Sets the stype of this RequestGetOfertas.


        :param stype: The stype of this RequestGetOfertas.
        :type stype: str
        """
        if stype is None:
            raise ValueError("Invalid value for `stype`, must not be `None`")  # noqa: E501

        self._stype = stype

    @property
    def external_transaction_id(self) -> str:
        """Gets the external_transaction_id of this RequestGetOfertas.


        :return: The external_transaction_id of this RequestGetOfertas.
        :rtype: str
        """
        return self._external_transaction_id

    @external_transaction_id.setter
    def external_transaction_id(self, external_transaction_id: str):
        """Sets the external_transaction_id of this RequestGetOfertas.


        :param external_transaction_id: The external_transaction_id of this RequestGetOfertas.
        :type external_transaction_id: str
        """
        if external_transaction_id is None:
            raise ValueError("Invalid value for `external_transaction_id`, must not be `None`")  # noqa: E501

        self._external_transaction_id = external_transaction_id
