# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class RequestGetBuro(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, channel: str=None, type: str=None):  # noqa: E501
        """RequestGetBuro - a model defined in Swagger

        :param channel: The channel of this RequestGetBuro.  # noqa: E501
        :type channel: str
        :param type: The type of this RequestGetBuro.  # noqa: E501
        :type type: str
        """
        self.swagger_types = {
            'channel': str,
            'type': str
        }

        self.attribute_map = {
            'channel': 'channel',
            'type': 'type'
        }
        self._channel = channel
        self._type = type

    @classmethod
    def from_dict(cls, dikt) -> 'RequestGetBuro':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The RequestGetBuro of this RequestGetBuro.  # noqa: E501
        :rtype: RequestGetBuro
        """
        return util.deserialize_model(dikt, cls)

    @property
    def channel(self) -> str:
        """Gets the channel of this RequestGetBuro.


        :return: The channel of this RequestGetBuro.
        :rtype: str
        """
        return self._channel

    @channel.setter
    def channel(self, channel: str):
        """Sets the channel of this RequestGetBuro.


        :param channel: The channel of this RequestGetBuro.
        :type channel: str
        """
        if channel is None:
            raise ValueError("Invalid value for `channel`, must not be `None`")  # noqa: E501

        self._channel = channel

    @property
    def type(self) -> str:
        """Gets the type of this RequestGetBuro.


        :return: The type of this RequestGetBuro.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type: str):
        """Sets the type of this RequestGetBuro.


        :param type: The type of this RequestGetBuro.
        :type type: str
        """
        if type is None:
            raise ValueError("Invalid value for `type`, must not be `None`")  # noqa: E501

        self._type = type
