# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class ResponseOfertasDataOFERTAS(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, oferta_id: int=None, oferta: str=None):  # noqa: E501
        """ResponseOfertasDataOFERTAS - a model defined in Swagger

        :param oferta_id: The oferta_id of this ResponseOfertasDataOFERTAS.  # noqa: E501
        :type oferta_id: int
        :param oferta: The oferta of this ResponseOfertasDataOFERTAS.  # noqa: E501
        :type oferta: str
        """
        self.swagger_types = {
            'oferta_id': int,
            'oferta': str
        }

        self.attribute_map = {
            'oferta_id': 'OFERTA_ID',
            'oferta': 'OFERTA'
        }
        self._oferta_id = oferta_id
        self._oferta = oferta

    @classmethod
    def from_dict(cls, dikt) -> 'ResponseOfertasDataOFERTAS':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ResponseOfertas_data_OFERTAS of this ResponseOfertasDataOFERTAS.  # noqa: E501
        :rtype: ResponseOfertasDataOFERTAS
        """
        return util.deserialize_model(dikt, cls)

    @property
    def oferta_id(self) -> int:
        """Gets the oferta_id of this ResponseOfertasDataOFERTAS.


        :return: The oferta_id of this ResponseOfertasDataOFERTAS.
        :rtype: int
        """
        return self._oferta_id

    @oferta_id.setter
    def oferta_id(self, oferta_id: int):
        """Sets the oferta_id of this ResponseOfertasDataOFERTAS.


        :param oferta_id: The oferta_id of this ResponseOfertasDataOFERTAS.
        :type oferta_id: int
        """

        self._oferta_id = oferta_id

    @property
    def oferta(self) -> str:
        """Gets the oferta of this ResponseOfertasDataOFERTAS.


        :return: The oferta of this ResponseOfertasDataOFERTAS.
        :rtype: str
        """
        return self._oferta

    @oferta.setter
    def oferta(self, oferta: str):
        """Sets the oferta of this ResponseOfertasDataOFERTAS.


        :param oferta: The oferta of this ResponseOfertasDataOFERTAS.
        :type oferta: str
        """

        self._oferta = oferta
