# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class ResponseGetPrecioRegularDataPRECIOREGULAR(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, precio: float=None):  # noqa: E501
        """ResponseGetPrecioRegularDataPRECIOREGULAR - a model defined in Swagger

        :param precio: The precio of this ResponseGetPrecioRegularDataPRECIOREGULAR.  # noqa: E501
        :type precio: float
        """
        self.swagger_types = {
            'precio': float
        }

        self.attribute_map = {
            'precio': 'PRECIO'
        }
        self._precio = precio

    @classmethod
    def from_dict(cls, dikt) -> 'ResponseGetPrecioRegularDataPRECIOREGULAR':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ResponseGetPrecioRegular_data_PRECIO_REGULAR of this ResponseGetPrecioRegularDataPRECIOREGULAR.  # noqa: E501
        :rtype: ResponseGetPrecioRegularDataPRECIOREGULAR
        """
        return util.deserialize_model(dikt, cls)

    @property
    def precio(self) -> float:
        """Gets the precio of this ResponseGetPrecioRegularDataPRECIOREGULAR.


        :return: The precio of this ResponseGetPrecioRegularDataPRECIOREGULAR.
        :rtype: float
        """
        return self._precio

    @precio.setter
    def precio(self, precio: float):
        """Sets the precio of this ResponseGetPrecioRegularDataPRECIOREGULAR.


        :param precio: The precio of this ResponseGetPrecioRegularDataPRECIOREGULAR.
        :type precio: float
        """

        self._precio = precio
