# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class ResponseGetUpgradeDataUPGRADE(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id: int=None, plan_upgrade: str=None):  # noqa: E501
        """ResponseGetUpgradeDataUPGRADE - a model defined in Swagger

        :param id: The id of this ResponseGetUpgradeDataUPGRADE.  # noqa: E501
        :type id: int
        :param plan_upgrade: The plan_upgrade of this ResponseGetUpgradeDataUPGRADE.  # noqa: E501
        :type plan_upgrade: str
        """
        self.swagger_types = {
            'id': int,
            'plan_upgrade': str
        }

        self.attribute_map = {
            'id': 'ID',
            'plan_upgrade': 'PLAN_UPGRADE'
        }
        self._id = id
        self._plan_upgrade = plan_upgrade

    @classmethod
    def from_dict(cls, dikt) -> 'ResponseGetUpgradeDataUPGRADE':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ResponseGetUpgrade_data_UPGRADE of this ResponseGetUpgradeDataUPGRADE.  # noqa: E501
        :rtype: ResponseGetUpgradeDataUPGRADE
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> int:
        """Gets the id of this ResponseGetUpgradeDataUPGRADE.


        :return: The id of this ResponseGetUpgradeDataUPGRADE.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """Sets the id of this ResponseGetUpgradeDataUPGRADE.


        :param id: The id of this ResponseGetUpgradeDataUPGRADE.
        :type id: int
        """

        self._id = id

    @property
    def plan_upgrade(self) -> str:
        """Gets the plan_upgrade of this ResponseGetUpgradeDataUPGRADE.


        :return: The plan_upgrade of this ResponseGetUpgradeDataUPGRADE.
        :rtype: str
        """
        return self._plan_upgrade

    @plan_upgrade.setter
    def plan_upgrade(self, plan_upgrade: str):
        """Sets the plan_upgrade of this ResponseGetUpgradeDataUPGRADE.


        :param plan_upgrade: The plan_upgrade of this ResponseGetUpgradeDataUPGRADE.
        :type plan_upgrade: str
        """

        self._plan_upgrade = plan_upgrade
