# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class ResponseCombosDataCOMBOPLAN(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, tariffplanid: int=None, tariffplan: str=None):  # noqa: E501
        """ResponseCombosDataCOMBOPLAN - a model defined in Swagger

        :param tariffplanid: The tariffplanid of this ResponseCombosDataCOMBOPLAN.  # noqa: E501
        :type tariffplanid: int
        :param tariffplan: The tariffplan of this ResponseCombosDataCOMBOPLAN.  # noqa: E501
        :type tariffplan: str
        """
        self.swagger_types = {
            'tariffplanid': int,
            'tariffplan': str
        }

        self.attribute_map = {
            'tariffplanid': 'TARIFFPLANID',
            'tariffplan': 'TARIFFPLAN'
        }
        self._tariffplanid = tariffplanid
        self._tariffplan = tariffplan

    @classmethod
    def from_dict(cls, dikt) -> 'ResponseCombosDataCOMBOPLAN':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ResponseCombos_data_COMBO_PLAN of this ResponseCombosDataCOMBOPLAN.  # noqa: E501
        :rtype: ResponseCombosDataCOMBOPLAN
        """
        return util.deserialize_model(dikt, cls)

    @property
    def tariffplanid(self) -> int:
        """Gets the tariffplanid of this ResponseCombosDataCOMBOPLAN.


        :return: The tariffplanid of this ResponseCombosDataCOMBOPLAN.
        :rtype: int
        """
        return self._tariffplanid

    @tariffplanid.setter
    def tariffplanid(self, tariffplanid: int):
        """Sets the tariffplanid of this ResponseCombosDataCOMBOPLAN.


        :param tariffplanid: The tariffplanid of this ResponseCombosDataCOMBOPLAN.
        :type tariffplanid: int
        """

        self._tariffplanid = tariffplanid

    @property
    def tariffplan(self) -> str:
        """Gets the tariffplan of this ResponseCombosDataCOMBOPLAN.


        :return: The tariffplan of this ResponseCombosDataCOMBOPLAN.
        :rtype: str
        """
        return self._tariffplan

    @tariffplan.setter
    def tariffplan(self, tariffplan: str):
        """Sets the tariffplan of this ResponseCombosDataCOMBOPLAN.


        :param tariffplan: The tariffplan of this ResponseCombosDataCOMBOPLAN.
        :type tariffplan: str
        """

        self._tariffplan = tariffplan
