# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class ResponseCombosDataCOMBOPRODUCTO(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, productid: int=None, producto: str=None):  # noqa: E501
        """ResponseCombosDataCOMBOPRODUCTO - a model defined in Swagger

        :param productid: The productid of this ResponseCombosDataCOMBOPRODUCTO.  # noqa: E501
        :type productid: int
        :param producto: The producto of this ResponseCombosDataCOMBOPRODUCTO.  # noqa: E501
        :type producto: str
        """
        self.swagger_types = {
            'productid': int,
            'producto': str
        }

        self.attribute_map = {
            'productid': 'PRODUCTID',
            'producto': 'PRODUCTO'
        }
        self._productid = productid
        self._producto = producto

    @classmethod
    def from_dict(cls, dikt) -> 'ResponseCombosDataCOMBOPRODUCTO':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ResponseCombos_data_COMBO_PRODUCTO of this ResponseCombosDataCOMBOPRODUCTO.  # noqa: E501
        :rtype: ResponseCombosDataCOMBOPRODUCTO
        """
        return util.deserialize_model(dikt, cls)

    @property
    def productid(self) -> int:
        """Gets the productid of this ResponseCombosDataCOMBOPRODUCTO.


        :return: The productid of this ResponseCombosDataCOMBOPRODUCTO.
        :rtype: int
        """
        return self._productid

    @productid.setter
    def productid(self, productid: int):
        """Sets the productid of this ResponseCombosDataCOMBOPRODUCTO.


        :param productid: The productid of this ResponseCombosDataCOMBOPRODUCTO.
        :type productid: int
        """

        self._productid = productid

    @property
    def producto(self) -> str:
        """Gets the producto of this ResponseCombosDataCOMBOPRODUCTO.


        :return: The producto of this ResponseCombosDataCOMBOPRODUCTO.
        :rtype: str
        """
        return self._producto

    @producto.setter
    def producto(self, producto: str):
        """Sets the producto of this ResponseCombosDataCOMBOPRODUCTO.


        :param producto: The producto of this ResponseCombosDataCOMBOPRODUCTO.
        :type producto: str
        """

        self._producto = producto
