# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class ResponseCombosDataCOMBOPLANVARIANT(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, tariffplanvariantid: int=None, tariffplanvariant: str=None):  # noqa: E501
        """ResponseCombosDataCOMBOPLANVARIANT - a model defined in Swagger

        :param tariffplanvariantid: The tariffplanvariantid of this ResponseCombosDataCOMBOPLANVARIANT.  # noqa: E501
        :type tariffplanvariantid: int
        :param tariffplanvariant: The tariffplanvariant of this ResponseCombosDataCOMBOPLANVARIANT.  # noqa: E501
        :type tariffplanvariant: str
        """
        self.swagger_types = {
            'tariffplanvariantid': int,
            'tariffplanvariant': str
        }

        self.attribute_map = {
            'tariffplanvariantid': 'TARIFFPLANVARIANTID',
            'tariffplanvariant': 'TARIFFPLANVARIANT'
        }
        self._tariffplanvariantid = tariffplanvariantid
        self._tariffplanvariant = tariffplanvariant

    @classmethod
    def from_dict(cls, dikt) -> 'ResponseCombosDataCOMBOPLANVARIANT':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ResponseCombos_data_COMBO_PLANVARIANT of this ResponseCombosDataCOMBOPLANVARIANT.  # noqa: E501
        :rtype: ResponseCombosDataCOMBOPLANVARIANT
        """
        return util.deserialize_model(dikt, cls)

    @property
    def tariffplanvariantid(self) -> int:
        """Gets the tariffplanvariantid of this ResponseCombosDataCOMBOPLANVARIANT.


        :return: The tariffplanvariantid of this ResponseCombosDataCOMBOPLANVARIANT.
        :rtype: int
        """
        return self._tariffplanvariantid

    @tariffplanvariantid.setter
    def tariffplanvariantid(self, tariffplanvariantid: int):
        """Sets the tariffplanvariantid of this ResponseCombosDataCOMBOPLANVARIANT.


        :param tariffplanvariantid: The tariffplanvariantid of this ResponseCombosDataCOMBOPLANVARIANT.
        :type tariffplanvariantid: int
        """

        self._tariffplanvariantid = tariffplanvariantid

    @property
    def tariffplanvariant(self) -> str:
        """Gets the tariffplanvariant of this ResponseCombosDataCOMBOPLANVARIANT.


        :return: The tariffplanvariant of this ResponseCombosDataCOMBOPLANVARIANT.
        :rtype: str
        """
        return self._tariffplanvariant

    @tariffplanvariant.setter
    def tariffplanvariant(self, tariffplanvariant: str):
        """Sets the tariffplanvariant of this ResponseCombosDataCOMBOPLANVARIANT.


        :param tariffplanvariant: The tariffplanvariant of this ResponseCombosDataCOMBOPLANVARIANT.
        :type tariffplanvariant: str
        """

        self._tariffplanvariant = tariffplanvariant
