# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.response_combos_data_comboplan import ResponseCombosDataCOMBOPLAN  # noqa: F401,E501
from swagger_server.models.response_combos_data_comboplanvariant import ResponseCombosDataCOMBOPLANVARIANT  # noqa: F401,E501
from swagger_server.models.response_combos_data_comboproducto import ResponseCombosDataCOMBOPRODUCTO  # noqa: F401,E501
from swagger_server import util


class ResponseCombosData(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, error_code: int=None, internal_transaction_id: str=None, external_transaction_id: str=None, message: str=None, combo_plan: ResponseCombosDataCOMBOPLAN=None, combo_planvariant: ResponseCombosDataCOMBOPLANVARIANT=None, combo_producto: ResponseCombosDataCOMBOPRODUCTO=None):  # noqa: E501
        """ResponseCombosData - a model defined in Swagger

        :param error_code: The error_code of this ResponseCombosData.  # noqa: E501
        :type error_code: int
        :param internal_transaction_id: The internal_transaction_id of this ResponseCombosData.  # noqa: E501
        :type internal_transaction_id: str
        :param external_transaction_id: The external_transaction_id of this ResponseCombosData.  # noqa: E501
        :type external_transaction_id: str
        :param message: The message of this ResponseCombosData.  # noqa: E501
        :type message: str
        :param combo_plan: The combo_plan of this ResponseCombosData.  # noqa: E501
        :type combo_plan: ResponseCombosDataCOMBOPLAN
        :param combo_planvariant: The combo_planvariant of this ResponseCombosData.  # noqa: E501
        :type combo_planvariant: ResponseCombosDataCOMBOPLANVARIANT
        :param combo_producto: The combo_producto of this ResponseCombosData.  # noqa: E501
        :type combo_producto: ResponseCombosDataCOMBOPRODUCTO
        """
        self.swagger_types = {
            'error_code': int,
            'internal_transaction_id': str,
            'external_transaction_id': str,
            'message': str,
            'combo_plan': ResponseCombosDataCOMBOPLAN,
            'combo_planvariant': ResponseCombosDataCOMBOPLANVARIANT,
            'combo_producto': ResponseCombosDataCOMBOPRODUCTO
        }

        self.attribute_map = {
            'error_code': 'errorCode',
            'internal_transaction_id': 'internalTransactionId',
            'external_transaction_id': 'externalTransactionId',
            'message': 'message',
            'combo_plan': 'COMBO_PLAN',
            'combo_planvariant': 'COMBO_PLANVARIANT',
            'combo_producto': 'COMBO_PRODUCTO'
        }
        self._error_code = error_code
        self._internal_transaction_id = internal_transaction_id
        self._external_transaction_id = external_transaction_id
        self._message = message
        self._combo_plan = combo_plan
        self._combo_planvariant = combo_planvariant
        self._combo_producto = combo_producto

    @classmethod
    def from_dict(cls, dikt) -> 'ResponseCombosData':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ResponseCombos_data of this ResponseCombosData.  # noqa: E501
        :rtype: ResponseCombosData
        """
        return util.deserialize_model(dikt, cls)

    @property
    def error_code(self) -> int:
        """Gets the error_code of this ResponseCombosData.


        :return: The error_code of this ResponseCombosData.
        :rtype: int
        """
        return self._error_code

    @error_code.setter
    def error_code(self, error_code: int):
        """Sets the error_code of this ResponseCombosData.


        :param error_code: The error_code of this ResponseCombosData.
        :type error_code: int
        """

        self._error_code = error_code

    @property
    def internal_transaction_id(self) -> str:
        """Gets the internal_transaction_id of this ResponseCombosData.


        :return: The internal_transaction_id of this ResponseCombosData.
        :rtype: str
        """
        return self._internal_transaction_id

    @internal_transaction_id.setter
    def internal_transaction_id(self, internal_transaction_id: str):
        """Sets the internal_transaction_id of this ResponseCombosData.


        :param internal_transaction_id: The internal_transaction_id of this ResponseCombosData.
        :type internal_transaction_id: str
        """

        self._internal_transaction_id = internal_transaction_id

    @property
    def external_transaction_id(self) -> str:
        """Gets the external_transaction_id of this ResponseCombosData.


        :return: The external_transaction_id of this ResponseCombosData.
        :rtype: str
        """
        return self._external_transaction_id

    @external_transaction_id.setter
    def external_transaction_id(self, external_transaction_id: str):
        """Sets the external_transaction_id of this ResponseCombosData.


        :param external_transaction_id: The external_transaction_id of this ResponseCombosData.
        :type external_transaction_id: str
        """

        self._external_transaction_id = external_transaction_id

    @property
    def message(self) -> str:
        """Gets the message of this ResponseCombosData.


        :return: The message of this ResponseCombosData.
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message: str):
        """Sets the message of this ResponseCombosData.


        :param message: The message of this ResponseCombosData.
        :type message: str
        """

        self._message = message

    @property
    def combo_plan(self) -> ResponseCombosDataCOMBOPLAN:
        """Gets the combo_plan of this ResponseCombosData.


        :return: The combo_plan of this ResponseCombosData.
        :rtype: ResponseCombosDataCOMBOPLAN
        """
        return self._combo_plan

    @combo_plan.setter
    def combo_plan(self, combo_plan: ResponseCombosDataCOMBOPLAN):
        """Sets the combo_plan of this ResponseCombosData.


        :param combo_plan: The combo_plan of this ResponseCombosData.
        :type combo_plan: ResponseCombosDataCOMBOPLAN
        """

        self._combo_plan = combo_plan

    @property
    def combo_planvariant(self) -> ResponseCombosDataCOMBOPLANVARIANT:
        """Gets the combo_planvariant of this ResponseCombosData.


        :return: The combo_planvariant of this ResponseCombosData.
        :rtype: ResponseCombosDataCOMBOPLANVARIANT
        """
        return self._combo_planvariant

    @combo_planvariant.setter
    def combo_planvariant(self, combo_planvariant: ResponseCombosDataCOMBOPLANVARIANT):
        """Sets the combo_planvariant of this ResponseCombosData.


        :param combo_planvariant: The combo_planvariant of this ResponseCombosData.
        :type combo_planvariant: ResponseCombosDataCOMBOPLANVARIANT
        """

        self._combo_planvariant = combo_planvariant

    @property
    def combo_producto(self) -> ResponseCombosDataCOMBOPRODUCTO:
        """Gets the combo_producto of this ResponseCombosData.


        :return: The combo_producto of this ResponseCombosData.
        :rtype: ResponseCombosDataCOMBOPRODUCTO
        """
        return self._combo_producto

    @combo_producto.setter
    def combo_producto(self, combo_producto: ResponseCombosDataCOMBOPRODUCTO):
        """Sets the combo_producto of this ResponseCombosData.


        :param combo_producto: The combo_producto of this ResponseCombosData.
        :type combo_producto: ResponseCombosDataCOMBOPRODUCTO
        """

        self._combo_producto = combo_producto
