# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.data_router import DataROUTER  # noqa: F401,E501
from swagger_server import util


class AllOfDataPostDiccionarioDatosRouter(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, modelo: int=None):  # noqa: E501
        """AllOfDataPostDiccionarioDatosRouter - a model defined in Swagger

        :param modelo: The modelo of this AllOfDataPostDiccionarioDatosRouter.  # noqa: E501
        :type modelo: int
        """
        self.swagger_types = {
            'modelo': int
        }

        self.attribute_map = {
            'modelo': 'Modelo'
        }
        self._modelo = modelo

    @classmethod
    def from_dict(cls, dikt) -> 'AllOfDataPostDiccionarioDatosRouter':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The AllOfDataPostDiccionarioDatosRouter of this AllOfDataPostDiccionarioDatosRouter.  # noqa: E501
        :rtype: AllOfDataPostDiccionarioDatosRouter
        """
        return util.deserialize_model(dikt, cls)

    @property
    def modelo(self) -> int:
        """Gets the modelo of this AllOfDataPostDiccionarioDatosRouter.


        :return: The modelo of this AllOfDataPostDiccionarioDatosRouter.
        :rtype: int
        """
        return self._modelo

    @modelo.setter
    def modelo(self, modelo: int):
        """Sets the modelo of this AllOfDataPostDiccionarioDatosRouter.


        :param modelo: The modelo of this AllOfDataPostDiccionarioDatosRouter.
        :type modelo: int
        """
        if modelo is None:
            raise ValueError("Invalid value for `modelo`, must not be `None`")  # noqa: E501

        self._modelo = modelo
