# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class RequestGetFinanciero(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, external_transaction_id: str=None, channel: str=None, type: str=None, v1: int=None, v2: int=None):  # noqa: E501
        """RequestGetFinanciero - a model defined in Swagger

        :param external_transaction_id: The external_transaction_id of this RequestGetFinanciero.  # noqa: E501
        :type external_transaction_id: str
        :param channel: The channel of this RequestGetFinanciero.  # noqa: E501
        :type channel: str
        :param type: The type of this RequestGetFinanciero.  # noqa: E501
        :type type: str
        :param v1: The v1 of this RequestGetFinanciero.  # noqa: E501
        :type v1: int
        :param v2: The v2 of this RequestGetFinanciero.  # noqa: E501
        :type v2: int
        """
        self.swagger_types = {
            'external_transaction_id': str,
            'channel': str,
            'type': str,
            'v1': int,
            'v2': int
        }

        self.attribute_map = {
            'external_transaction_id': 'externalTransactionId',
            'channel': 'channel',
            'type': 'type',
            'v1': '_V1',
            'v2': '_V2'
        }
        self._external_transaction_id = external_transaction_id
        self._channel = channel
        self._type = type
        self._v1 = v1
        self._v2 = v2

    @classmethod
    def from_dict(cls, dikt) -> 'RequestGetFinanciero':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The RequestGetFinanciero of this RequestGetFinanciero.  # noqa: E501
        :rtype: RequestGetFinanciero
        """
        return util.deserialize_model(dikt, cls)

    @property
    def external_transaction_id(self) -> str:
        """Gets the external_transaction_id of this RequestGetFinanciero.


        :return: The external_transaction_id of this RequestGetFinanciero.
        :rtype: str
        """
        return self._external_transaction_id

    @external_transaction_id.setter
    def external_transaction_id(self, external_transaction_id: str):
        """Sets the external_transaction_id of this RequestGetFinanciero.


        :param external_transaction_id: The external_transaction_id of this RequestGetFinanciero.
        :type external_transaction_id: str
        """
        if external_transaction_id is None:
            raise ValueError("Invalid value for `external_transaction_id`, must not be `None`")  # noqa: E501

        self._external_transaction_id = external_transaction_id

    @property
    def channel(self) -> str:
        """Gets the channel of this RequestGetFinanciero.


        :return: The channel of this RequestGetFinanciero.
        :rtype: str
        """
        return self._channel

    @channel.setter
    def channel(self, channel: str):
        """Sets the channel of this RequestGetFinanciero.


        :param channel: The channel of this RequestGetFinanciero.
        :type channel: str
        """
        if channel is None:
            raise ValueError("Invalid value for `channel`, must not be `None`")  # noqa: E501

        self._channel = channel

    @property
    def type(self) -> str:
        """Gets the type of this RequestGetFinanciero.


        :return: The type of this RequestGetFinanciero.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type: str):
        """Sets the type of this RequestGetFinanciero.


        :param type: The type of this RequestGetFinanciero.
        :type type: str
        """
        if type is None:
            raise ValueError("Invalid value for `type`, must not be `None`")  # noqa: E501

        self._type = type

    @property
    def v1(self) -> int:
        """Gets the v1 of this RequestGetFinanciero.


        :return: The v1 of this RequestGetFinanciero.
        :rtype: int
        """
        return self._v1

    @v1.setter
    def v1(self, v1: int):
        """Sets the v1 of this RequestGetFinanciero.


        :param v1: The v1 of this RequestGetFinanciero.
        :type v1: int
        """

        self._v1 = v1

    @property
    def v2(self) -> int:
        """Gets the v2 of this RequestGetFinanciero.


        :return: The v2 of this RequestGetFinanciero.
        :rtype: int
        """
        return self._v2

    @v2.setter
    def v2(self, v2: int):
        """Sets the v2 of this RequestGetFinanciero.


        :param v2: The v2 of this RequestGetFinanciero.
        :type v2: int
        """

        self._v2 = v2
