# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class ResponseGetSectoresSECTORS(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, ciudad: str=None, sector: str=None, sector_id: int=None):  # noqa: E501
        """ResponseGetSectoresSECTORS - a model defined in Swagger

        :param ciudad: The ciudad of this ResponseGetSectoresSECTORS.  # noqa: E501
        :type ciudad: str
        :param sector: The sector of this ResponseGetSectoresSECTORS.  # noqa: E501
        :type sector: str
        :param sector_id: The sector_id of this ResponseGetSectoresSECTORS.  # noqa: E501
        :type sector_id: int
        """
        self.swagger_types = {
            'ciudad': str,
            'sector': str,
            'sector_id': int
        }

        self.attribute_map = {
            'ciudad': 'CIUDAD',
            'sector': 'SECTOR',
            'sector_id': 'SECTOR_ID'
        }
        self._ciudad = ciudad
        self._sector = sector
        self._sector_id = sector_id

    @classmethod
    def from_dict(cls, dikt) -> 'ResponseGetSectoresSECTORS':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ResponseGetSectores_SECTORS of this ResponseGetSectoresSECTORS.  # noqa: E501
        :rtype: ResponseGetSectoresSECTORS
        """
        return util.deserialize_model(dikt, cls)

    @property
    def ciudad(self) -> str:
        """Gets the ciudad of this ResponseGetSectoresSECTORS.


        :return: The ciudad of this ResponseGetSectoresSECTORS.
        :rtype: str
        """
        return self._ciudad

    @ciudad.setter
    def ciudad(self, ciudad: str):
        """Sets the ciudad of this ResponseGetSectoresSECTORS.


        :param ciudad: The ciudad of this ResponseGetSectoresSECTORS.
        :type ciudad: str
        """

        self._ciudad = ciudad

    @property
    def sector(self) -> str:
        """Gets the sector of this ResponseGetSectoresSECTORS.


        :return: The sector of this ResponseGetSectoresSECTORS.
        :rtype: str
        """
        return self._sector

    @sector.setter
    def sector(self, sector: str):
        """Sets the sector of this ResponseGetSectoresSECTORS.


        :param sector: The sector of this ResponseGetSectoresSECTORS.
        :type sector: str
        """

        self._sector = sector

    @property
    def sector_id(self) -> int:
        """Gets the sector_id of this ResponseGetSectoresSECTORS.


        :return: The sector_id of this ResponseGetSectoresSECTORS.
        :rtype: int
        """
        return self._sector_id

    @sector_id.setter
    def sector_id(self, sector_id: int):
        """Sets the sector_id of this ResponseGetSectoresSECTORS.


        :param sector_id: The sector_id of this ResponseGetSectoresSECTORS.
        :type sector_id: int
        """

        self._sector_id = sector_id
