# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.response_get_combo_producto_comboproducto import ResponseGetComboProductoCOMBOPRODUCTO  # noqa: F401,E501
from swagger_server import util


class ResponseGetComboProducto(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, error_code: int=None, combo_producto: List[ResponseGetComboProductoCOMBOPRODUCTO]=None, internal_transaction_id: int=None, external_transaction_id: int=None, message: str=None):  # noqa: E501
        """ResponseGetComboProducto - a model defined in Swagger

        :param error_code: The error_code of this ResponseGetComboProducto.  # noqa: E501
        :type error_code: int
        :param combo_producto: The combo_producto of this ResponseGetComboProducto.  # noqa: E501
        :type combo_producto: List[ResponseGetComboProductoCOMBOPRODUCTO]
        :param internal_transaction_id: The internal_transaction_id of this ResponseGetComboProducto.  # noqa: E501
        :type internal_transaction_id: int
        :param external_transaction_id: The external_transaction_id of this ResponseGetComboProducto.  # noqa: E501
        :type external_transaction_id: int
        :param message: The message of this ResponseGetComboProducto.  # noqa: E501
        :type message: str
        """
        self.swagger_types = {
            'error_code': int,
            'combo_producto': List[ResponseGetComboProductoCOMBOPRODUCTO],
            'internal_transaction_id': int,
            'external_transaction_id': int,
            'message': str
        }

        self.attribute_map = {
            'error_code': 'errorCode',
            'combo_producto': 'COMBO_PRODUCTO',
            'internal_transaction_id': 'internalTransactionId',
            'external_transaction_id': 'externalTransactionId',
            'message': 'message'
        }
        self._error_code = error_code
        self._combo_producto = combo_producto
        self._internal_transaction_id = internal_transaction_id
        self._external_transaction_id = external_transaction_id
        self._message = message

    @classmethod
    def from_dict(cls, dikt) -> 'ResponseGetComboProducto':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ResponseGetCombo_Producto of this ResponseGetComboProducto.  # noqa: E501
        :rtype: ResponseGetComboProducto
        """
        return util.deserialize_model(dikt, cls)

    @property
    def error_code(self) -> int:
        """Gets the error_code of this ResponseGetComboProducto.


        :return: The error_code of this ResponseGetComboProducto.
        :rtype: int
        """
        return self._error_code

    @error_code.setter
    def error_code(self, error_code: int):
        """Sets the error_code of this ResponseGetComboProducto.


        :param error_code: The error_code of this ResponseGetComboProducto.
        :type error_code: int
        """

        self._error_code = error_code

    @property
    def combo_producto(self) -> List[ResponseGetComboProductoCOMBOPRODUCTO]:
        """Gets the combo_producto of this ResponseGetComboProducto.


        :return: The combo_producto of this ResponseGetComboProducto.
        :rtype: List[ResponseGetComboProductoCOMBOPRODUCTO]
        """
        return self._combo_producto

    @combo_producto.setter
    def combo_producto(self, combo_producto: List[ResponseGetComboProductoCOMBOPRODUCTO]):
        """Sets the combo_producto of this ResponseGetComboProducto.


        :param combo_producto: The combo_producto of this ResponseGetComboProducto.
        :type combo_producto: List[ResponseGetComboProductoCOMBOPRODUCTO]
        """

        self._combo_producto = combo_producto

    @property
    def internal_transaction_id(self) -> int:
        """Gets the internal_transaction_id of this ResponseGetComboProducto.


        :return: The internal_transaction_id of this ResponseGetComboProducto.
        :rtype: int
        """
        return self._internal_transaction_id

    @internal_transaction_id.setter
    def internal_transaction_id(self, internal_transaction_id: int):
        """Sets the internal_transaction_id of this ResponseGetComboProducto.


        :param internal_transaction_id: The internal_transaction_id of this ResponseGetComboProducto.
        :type internal_transaction_id: int
        """

        self._internal_transaction_id = internal_transaction_id

    @property
    def external_transaction_id(self) -> int:
        """Gets the external_transaction_id of this ResponseGetComboProducto.


        :return: The external_transaction_id of this ResponseGetComboProducto.
        :rtype: int
        """
        return self._external_transaction_id

    @external_transaction_id.setter
    def external_transaction_id(self, external_transaction_id: int):
        """Sets the external_transaction_id of this ResponseGetComboProducto.


        :param external_transaction_id: The external_transaction_id of this ResponseGetComboProducto.
        :type external_transaction_id: int
        """

        self._external_transaction_id = external_transaction_id

    @property
    def message(self) -> str:
        """Gets the message of this ResponseGetComboProducto.


        :return: The message of this ResponseGetComboProducto.
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message: str):
        """Sets the message of this ResponseGetComboProducto.


        :param message: The message of this ResponseGetComboProducto.
        :type message: str
        """

        self._message = message
