# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class ResponseGetComboPlanVariantCOMBOPLANVARIANT(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, tariffplanvariant: str=None, tariffplanvariantid: int=None):  # noqa: E501
        """ResponseGetComboPlanVariantCOMBOPLANVARIANT - a model defined in Swagger

        :param tariffplanvariant: The tariffplanvariant of this ResponseGetComboPlanVariantCOMBOPLANVARIANT.  # noqa: E501
        :type tariffplanvariant: str
        :param tariffplanvariantid: The tariffplanvariantid of this ResponseGetComboPlanVariantCOMBOPLANVARIANT.  # noqa: E501
        :type tariffplanvariantid: int
        """
        self.swagger_types = {
            'tariffplanvariant': str,
            'tariffplanvariantid': int
        }

        self.attribute_map = {
            'tariffplanvariant': 'TARIFFPLANVARIANT',
            'tariffplanvariantid': 'TARIFFPLANVARIANTID'
        }
        self._tariffplanvariant = tariffplanvariant
        self._tariffplanvariantid = tariffplanvariantid

    @classmethod
    def from_dict(cls, dikt) -> 'ResponseGetComboPlanVariantCOMBOPLANVARIANT':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ResponseGetCombo_PlanVariant_COMBO_PLANVARIANT of this ResponseGetComboPlanVariantCOMBOPLANVARIANT.  # noqa: E501
        :rtype: ResponseGetComboPlanVariantCOMBOPLANVARIANT
        """
        return util.deserialize_model(dikt, cls)

    @property
    def tariffplanvariant(self) -> str:
        """Gets the tariffplanvariant of this ResponseGetComboPlanVariantCOMBOPLANVARIANT.


        :return: The tariffplanvariant of this ResponseGetComboPlanVariantCOMBOPLANVARIANT.
        :rtype: str
        """
        return self._tariffplanvariant

    @tariffplanvariant.setter
    def tariffplanvariant(self, tariffplanvariant: str):
        """Sets the tariffplanvariant of this ResponseGetComboPlanVariantCOMBOPLANVARIANT.


        :param tariffplanvariant: The tariffplanvariant of this ResponseGetComboPlanVariantCOMBOPLANVARIANT.
        :type tariffplanvariant: str
        """

        self._tariffplanvariant = tariffplanvariant

    @property
    def tariffplanvariantid(self) -> int:
        """Gets the tariffplanvariantid of this ResponseGetComboPlanVariantCOMBOPLANVARIANT.


        :return: The tariffplanvariantid of this ResponseGetComboPlanVariantCOMBOPLANVARIANT.
        :rtype: int
        """
        return self._tariffplanvariantid

    @tariffplanvariantid.setter
    def tariffplanvariantid(self, tariffplanvariantid: int):
        """Sets the tariffplanvariantid of this ResponseGetComboPlanVariantCOMBOPLANVARIANT.


        :param tariffplanvariantid: The tariffplanvariantid of this ResponseGetComboPlanVariantCOMBOPLANVARIANT.
        :type tariffplanvariantid: int
        """

        self._tariffplanvariantid = tariffplanvariantid
