# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.response_get_upgrade_upgrade import ResponseGetUpgradeUPGRADE  # noqa: F401,E501
from swagger_server import util


class ResponseGetUpgrade(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, error_code: int=None, upgrade: List[ResponseGetUpgradeUPGRADE]=None, internal_transaction_id: int=None, external_transaction_id: int=None, message: str=None):  # noqa: E501
        """ResponseGetUpgrade - a model defined in Swagger

        :param error_code: The error_code of this ResponseGetUpgrade.  # noqa: E501
        :type error_code: int
        :param upgrade: The upgrade of this ResponseGetUpgrade.  # noqa: E501
        :type upgrade: List[ResponseGetUpgradeUPGRADE]
        :param internal_transaction_id: The internal_transaction_id of this ResponseGetUpgrade.  # noqa: E501
        :type internal_transaction_id: int
        :param external_transaction_id: The external_transaction_id of this ResponseGetUpgrade.  # noqa: E501
        :type external_transaction_id: int
        :param message: The message of this ResponseGetUpgrade.  # noqa: E501
        :type message: str
        """
        self.swagger_types = {
            'error_code': int,
            'upgrade': List[ResponseGetUpgradeUPGRADE],
            'internal_transaction_id': int,
            'external_transaction_id': int,
            'message': str
        }

        self.attribute_map = {
            'error_code': 'errorCode',
            'upgrade': 'UPGRADE',
            'internal_transaction_id': 'internalTransactionId',
            'external_transaction_id': 'externalTransactionId',
            'message': 'message'
        }
        self._error_code = error_code
        self._upgrade = upgrade
        self._internal_transaction_id = internal_transaction_id
        self._external_transaction_id = external_transaction_id
        self._message = message

    @classmethod
    def from_dict(cls, dikt) -> 'ResponseGetUpgrade':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ResponseGetUpgrade of this ResponseGetUpgrade.  # noqa: E501
        :rtype: ResponseGetUpgrade
        """
        return util.deserialize_model(dikt, cls)

    @property
    def error_code(self) -> int:
        """Gets the error_code of this ResponseGetUpgrade.


        :return: The error_code of this ResponseGetUpgrade.
        :rtype: int
        """
        return self._error_code

    @error_code.setter
    def error_code(self, error_code: int):
        """Sets the error_code of this ResponseGetUpgrade.


        :param error_code: The error_code of this ResponseGetUpgrade.
        :type error_code: int
        """

        self._error_code = error_code

    @property
    def upgrade(self) -> List[ResponseGetUpgradeUPGRADE]:
        """Gets the upgrade of this ResponseGetUpgrade.


        :return: The upgrade of this ResponseGetUpgrade.
        :rtype: List[ResponseGetUpgradeUPGRADE]
        """
        return self._upgrade

    @upgrade.setter
    def upgrade(self, upgrade: List[ResponseGetUpgradeUPGRADE]):
        """Sets the upgrade of this ResponseGetUpgrade.


        :param upgrade: The upgrade of this ResponseGetUpgrade.
        :type upgrade: List[ResponseGetUpgradeUPGRADE]
        """

        self._upgrade = upgrade

    @property
    def internal_transaction_id(self) -> int:
        """Gets the internal_transaction_id of this ResponseGetUpgrade.


        :return: The internal_transaction_id of this ResponseGetUpgrade.
        :rtype: int
        """
        return self._internal_transaction_id

    @internal_transaction_id.setter
    def internal_transaction_id(self, internal_transaction_id: int):
        """Sets the internal_transaction_id of this ResponseGetUpgrade.


        :param internal_transaction_id: The internal_transaction_id of this ResponseGetUpgrade.
        :type internal_transaction_id: int
        """

        self._internal_transaction_id = internal_transaction_id

    @property
    def external_transaction_id(self) -> int:
        """Gets the external_transaction_id of this ResponseGetUpgrade.


        :return: The external_transaction_id of this ResponseGetUpgrade.
        :rtype: int
        """
        return self._external_transaction_id

    @external_transaction_id.setter
    def external_transaction_id(self, external_transaction_id: int):
        """Sets the external_transaction_id of this ResponseGetUpgrade.


        :param external_transaction_id: The external_transaction_id of this ResponseGetUpgrade.
        :type external_transaction_id: int
        """

        self._external_transaction_id = external_transaction_id

    @property
    def message(self) -> str:
        """Gets the message of this ResponseGetUpgrade.


        :return: The message of this ResponseGetUpgrade.
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message: str):
        """Sets the message of this ResponseGetUpgrade.


        :param message: The message of this ResponseGetUpgrade.
        :type message: str
        """

        self._message = message
