# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.response_get_dias_gozados_diasgozados import ResponseGetDiasGozadosDIASGOZADOS  # noqa: F401,E501
from swagger_server import util


class ResponseGetDiasGozados(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, error_code: int=None, dias_gozados: List[ResponseGetDiasGozadosDIASGOZADOS]=None, internal_transaction_id: int=None, external_transaction_id: int=None, message: str=None):  # noqa: E501
        """ResponseGetDiasGozados - a model defined in Swagger

        :param error_code: The error_code of this ResponseGetDiasGozados.  # noqa: E501
        :type error_code: int
        :param dias_gozados: The dias_gozados of this ResponseGetDiasGozados.  # noqa: E501
        :type dias_gozados: List[ResponseGetDiasGozadosDIASGOZADOS]
        :param internal_transaction_id: The internal_transaction_id of this ResponseGetDiasGozados.  # noqa: E501
        :type internal_transaction_id: int
        :param external_transaction_id: The external_transaction_id of this ResponseGetDiasGozados.  # noqa: E501
        :type external_transaction_id: int
        :param message: The message of this ResponseGetDiasGozados.  # noqa: E501
        :type message: str
        """
        self.swagger_types = {
            'error_code': int,
            'dias_gozados': List[ResponseGetDiasGozadosDIASGOZADOS],
            'internal_transaction_id': int,
            'external_transaction_id': int,
            'message': str
        }

        self.attribute_map = {
            'error_code': 'errorCode',
            'dias_gozados': 'DIAS_GOZADOS',
            'internal_transaction_id': 'internalTransactionId',
            'external_transaction_id': 'externalTransactionId',
            'message': 'message'
        }
        self._error_code = error_code
        self._dias_gozados = dias_gozados
        self._internal_transaction_id = internal_transaction_id
        self._external_transaction_id = external_transaction_id
        self._message = message

    @classmethod
    def from_dict(cls, dikt) -> 'ResponseGetDiasGozados':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ResponseGetDias_Gozados of this ResponseGetDiasGozados.  # noqa: E501
        :rtype: ResponseGetDiasGozados
        """
        return util.deserialize_model(dikt, cls)

    @property
    def error_code(self) -> int:
        """Gets the error_code of this ResponseGetDiasGozados.


        :return: The error_code of this ResponseGetDiasGozados.
        :rtype: int
        """
        return self._error_code

    @error_code.setter
    def error_code(self, error_code: int):
        """Sets the error_code of this ResponseGetDiasGozados.


        :param error_code: The error_code of this ResponseGetDiasGozados.
        :type error_code: int
        """

        self._error_code = error_code

    @property
    def dias_gozados(self) -> List[ResponseGetDiasGozadosDIASGOZADOS]:
        """Gets the dias_gozados of this ResponseGetDiasGozados.


        :return: The dias_gozados of this ResponseGetDiasGozados.
        :rtype: List[ResponseGetDiasGozadosDIASGOZADOS]
        """
        return self._dias_gozados

    @dias_gozados.setter
    def dias_gozados(self, dias_gozados: List[ResponseGetDiasGozadosDIASGOZADOS]):
        """Sets the dias_gozados of this ResponseGetDiasGozados.


        :param dias_gozados: The dias_gozados of this ResponseGetDiasGozados.
        :type dias_gozados: List[ResponseGetDiasGozadosDIASGOZADOS]
        """

        self._dias_gozados = dias_gozados

    @property
    def internal_transaction_id(self) -> int:
        """Gets the internal_transaction_id of this ResponseGetDiasGozados.


        :return: The internal_transaction_id of this ResponseGetDiasGozados.
        :rtype: int
        """
        return self._internal_transaction_id

    @internal_transaction_id.setter
    def internal_transaction_id(self, internal_transaction_id: int):
        """Sets the internal_transaction_id of this ResponseGetDiasGozados.


        :param internal_transaction_id: The internal_transaction_id of this ResponseGetDiasGozados.
        :type internal_transaction_id: int
        """

        self._internal_transaction_id = internal_transaction_id

    @property
    def external_transaction_id(self) -> int:
        """Gets the external_transaction_id of this ResponseGetDiasGozados.


        :return: The external_transaction_id of this ResponseGetDiasGozados.
        :rtype: int
        """
        return self._external_transaction_id

    @external_transaction_id.setter
    def external_transaction_id(self, external_transaction_id: int):
        """Sets the external_transaction_id of this ResponseGetDiasGozados.


        :param external_transaction_id: The external_transaction_id of this ResponseGetDiasGozados.
        :type external_transaction_id: int
        """

        self._external_transaction_id = external_transaction_id

    @property
    def message(self) -> str:
        """Gets the message of this ResponseGetDiasGozados.


        :return: The message of this ResponseGetDiasGozados.
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message: str):
        """Sets the message of this ResponseGetDiasGozados.


        :param message: The message of this ResponseGetDiasGozados.
        :type message: str
        """

        self._message = message
