# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class RequestGetLugares(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, external_transaction_id: str=None, channel: str=None, type: str=None, tariffplanvariant: int=None, productoid: int=None, id_prov: int=None, id_provs: List[int]=None, id_city: int=None, id_cities: List[int]=None):  # noqa: E501
        """RequestGetLugares - a model defined in Swagger

        :param external_transaction_id: The external_transaction_id of this RequestGetLugares.  # noqa: E501
        :type external_transaction_id: str
        :param channel: The channel of this RequestGetLugares.  # noqa: E501
        :type channel: str
        :param type: The type of this RequestGetLugares.  # noqa: E501
        :type type: str
        :param tariffplanvariant: The tariffplanvariant of this RequestGetLugares.  # noqa: E501
        :type tariffplanvariant: int
        :param productoid: The productoid of this RequestGetLugares.  # noqa: E501
        :type productoid: int
        :param id_prov: The id_prov of this RequestGetLugares.  # noqa: E501
        :type id_prov: int
        :param id_provs: The id_provs of this RequestGetLugares.  # noqa: E501
        :type id_provs: List[int]
        :param id_city: The id_city of this RequestGetLugares.  # noqa: E501
        :type id_city: int
        :param id_cities: The id_cities of this RequestGetLugares.  # noqa: E501
        :type id_cities: List[int]
        """
        self.swagger_types = {
            'external_transaction_id': str,
            'channel': str,
            'type': str,
            'tariffplanvariant': int,
            'productoid': int,
            'id_prov': int,
            'id_provs': List[int],
            'id_city': int,
            'id_cities': List[int]
        }

        self.attribute_map = {
            'external_transaction_id': 'externalTransactionId',
            'channel': 'channel',
            'type': 'type',
            'tariffplanvariant': 'TARIFFPLANVARIANT',
            'productoid': 'PRODUCTOID',
            'id_prov': 'id_Prov',
            'id_provs': 'id_Provs',
            'id_city': 'id_City',
            'id_cities': 'id_Cities'
        }
        self._external_transaction_id = external_transaction_id
        self._channel = channel
        self._type = type
        self._tariffplanvariant = tariffplanvariant
        self._productoid = productoid
        self._id_prov = id_prov
        self._id_provs = id_provs
        self._id_city = id_city
        self._id_cities = id_cities

    @classmethod
    def from_dict(cls, dikt) -> 'RequestGetLugares':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The RequestGetLugares of this RequestGetLugares.  # noqa: E501
        :rtype: RequestGetLugares
        """
        return util.deserialize_model(dikt, cls)

    @property
    def external_transaction_id(self) -> str:
        """Gets the external_transaction_id of this RequestGetLugares.


        :return: The external_transaction_id of this RequestGetLugares.
        :rtype: str
        """
        return self._external_transaction_id

    @external_transaction_id.setter
    def external_transaction_id(self, external_transaction_id: str):
        """Sets the external_transaction_id of this RequestGetLugares.


        :param external_transaction_id: The external_transaction_id of this RequestGetLugares.
        :type external_transaction_id: str
        """
        if external_transaction_id is None:
            raise ValueError("Invalid value for `external_transaction_id`, must not be `None`")  # noqa: E501

        self._external_transaction_id = external_transaction_id

    @property
    def channel(self) -> str:
        """Gets the channel of this RequestGetLugares.


        :return: The channel of this RequestGetLugares.
        :rtype: str
        """
        return self._channel

    @channel.setter
    def channel(self, channel: str):
        """Sets the channel of this RequestGetLugares.


        :param channel: The channel of this RequestGetLugares.
        :type channel: str
        """
        if channel is None:
            raise ValueError("Invalid value for `channel`, must not be `None`")  # noqa: E501

        self._channel = channel

    @property
    def type(self) -> str:
        """Gets the type of this RequestGetLugares.


        :return: The type of this RequestGetLugares.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type: str):
        """Sets the type of this RequestGetLugares.


        :param type: The type of this RequestGetLugares.
        :type type: str
        """
        if type is None:
            raise ValueError("Invalid value for `type`, must not be `None`")  # noqa: E501

        self._type = type

    @property
    def tariffplanvariant(self) -> int:
        """Gets the tariffplanvariant of this RequestGetLugares.


        :return: The tariffplanvariant of this RequestGetLugares.
        :rtype: int
        """
        return self._tariffplanvariant

    @tariffplanvariant.setter
    def tariffplanvariant(self, tariffplanvariant: int):
        """Sets the tariffplanvariant of this RequestGetLugares.


        :param tariffplanvariant: The tariffplanvariant of this RequestGetLugares.
        :type tariffplanvariant: int
        """

        self._tariffplanvariant = tariffplanvariant

    @property
    def productoid(self) -> int:
        """Gets the productoid of this RequestGetLugares.


        :return: The productoid of this RequestGetLugares.
        :rtype: int
        """
        return self._productoid

    @productoid.setter
    def productoid(self, productoid: int):
        """Sets the productoid of this RequestGetLugares.


        :param productoid: The productoid of this RequestGetLugares.
        :type productoid: int
        """

        self._productoid = productoid

    @property
    def id_prov(self) -> int:
        """Gets the id_prov of this RequestGetLugares.


        :return: The id_prov of this RequestGetLugares.
        :rtype: int
        """
        return self._id_prov

    @id_prov.setter
    def id_prov(self, id_prov: int):
        """Sets the id_prov of this RequestGetLugares.


        :param id_prov: The id_prov of this RequestGetLugares.
        :type id_prov: int
        """

        self._id_prov = id_prov

    @property
    def id_provs(self) -> List[int]:
        """Gets the id_provs of this RequestGetLugares.


        :return: The id_provs of this RequestGetLugares.
        :rtype: List[int]
        """
        return self._id_provs

    @id_provs.setter
    def id_provs(self, id_provs: List[int]):
        """Sets the id_provs of this RequestGetLugares.


        :param id_provs: The id_provs of this RequestGetLugares.
        :type id_provs: List[int]
        """

        self._id_provs = id_provs

    @property
    def id_city(self) -> int:
        """Gets the id_city of this RequestGetLugares.


        :return: The id_city of this RequestGetLugares.
        :rtype: int
        """
        return self._id_city

    @id_city.setter
    def id_city(self, id_city: int):
        """Sets the id_city of this RequestGetLugares.


        :param id_city: The id_city of this RequestGetLugares.
        :type id_city: int
        """

        self._id_city = id_city

    @property
    def id_cities(self) -> List[int]:
        """Gets the id_cities of this RequestGetLugares.


        :return: The id_cities of this RequestGetLugares.
        :rtype: List[int]
        """
        return self._id_cities

    @id_cities.setter
    def id_cities(self, id_cities: List[int]):
        """Sets the id_cities of this RequestGetLugares.


        :param id_cities: The id_cities of this RequestGetLugares.
        :type id_cities: List[int]
        """

        self._id_cities = id_cities
