# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class RequestGetFinanciero(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, external_transaction_id: str=None, channel: str=None, type: str=None, id_prod: int=None, tariffplan: int=None, tariffplanvariant: int=None):  # noqa: E501
        """RequestGetFinanciero - a model defined in Swagger

        :param external_transaction_id: The external_transaction_id of this RequestGetFinanciero.  # noqa: E501
        :type external_transaction_id: str
        :param channel: The channel of this RequestGetFinanciero.  # noqa: E501
        :type channel: str
        :param type: The type of this RequestGetFinanciero.  # noqa: E501
        :type type: str
        :param id_prod: The id_prod of this RequestGetFinanciero.  # noqa: E501
        :type id_prod: int
        :param tariffplan: The tariffplan of this RequestGetFinanciero.  # noqa: E501
        :type tariffplan: int
        :param tariffplanvariant: The tariffplanvariant of this RequestGetFinanciero.  # noqa: E501
        :type tariffplanvariant: int
        """
        self.swagger_types = {
            'external_transaction_id': str,
            'channel': str,
            'type': str,
            'id_prod': int,
            'tariffplan': int,
            'tariffplanvariant': int
        }

        self.attribute_map = {
            'external_transaction_id': 'externalTransactionId',
            'channel': 'channel',
            'type': 'type',
            'id_prod': 'id_Prod',
            'tariffplan': 'TARIFFPLAN',
            'tariffplanvariant': 'TARIFFPLANVARIANT'
        }
        self._external_transaction_id = external_transaction_id
        self._channel = channel
        self._type = type
        self._id_prod = id_prod
        self._tariffplan = tariffplan
        self._tariffplanvariant = tariffplanvariant

    @classmethod
    def from_dict(cls, dikt) -> 'RequestGetFinanciero':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The RequestGetFinanciero of this RequestGetFinanciero.  # noqa: E501
        :rtype: RequestGetFinanciero
        """
        return util.deserialize_model(dikt, cls)

    @property
    def external_transaction_id(self) -> str:
        """Gets the external_transaction_id of this RequestGetFinanciero.


        :return: The external_transaction_id of this RequestGetFinanciero.
        :rtype: str
        """
        return self._external_transaction_id

    @external_transaction_id.setter
    def external_transaction_id(self, external_transaction_id: str):
        """Sets the external_transaction_id of this RequestGetFinanciero.


        :param external_transaction_id: The external_transaction_id of this RequestGetFinanciero.
        :type external_transaction_id: str
        """
        if external_transaction_id is None:
            raise ValueError("Invalid value for `external_transaction_id`, must not be `None`")  # noqa: E501

        self._external_transaction_id = external_transaction_id

    @property
    def channel(self) -> str:
        """Gets the channel of this RequestGetFinanciero.


        :return: The channel of this RequestGetFinanciero.
        :rtype: str
        """
        return self._channel

    @channel.setter
    def channel(self, channel: str):
        """Sets the channel of this RequestGetFinanciero.


        :param channel: The channel of this RequestGetFinanciero.
        :type channel: str
        """
        if channel is None:
            raise ValueError("Invalid value for `channel`, must not be `None`")  # noqa: E501

        self._channel = channel

    @property
    def type(self) -> str:
        """Gets the type of this RequestGetFinanciero.


        :return: The type of this RequestGetFinanciero.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type: str):
        """Sets the type of this RequestGetFinanciero.


        :param type: The type of this RequestGetFinanciero.
        :type type: str
        """
        if type is None:
            raise ValueError("Invalid value for `type`, must not be `None`")  # noqa: E501

        self._type = type

    @property
    def id_prod(self) -> int:
        """Gets the id_prod of this RequestGetFinanciero.


        :return: The id_prod of this RequestGetFinanciero.
        :rtype: int
        """
        return self._id_prod

    @id_prod.setter
    def id_prod(self, id_prod: int):
        """Sets the id_prod of this RequestGetFinanciero.


        :param id_prod: The id_prod of this RequestGetFinanciero.
        :type id_prod: int
        """

        self._id_prod = id_prod

    @property
    def tariffplan(self) -> int:
        """Gets the tariffplan of this RequestGetFinanciero.


        :return: The tariffplan of this RequestGetFinanciero.
        :rtype: int
        """
        return self._tariffplan

    @tariffplan.setter
    def tariffplan(self, tariffplan: int):
        """Sets the tariffplan of this RequestGetFinanciero.


        :param tariffplan: The tariffplan of this RequestGetFinanciero.
        :type tariffplan: int
        """

        self._tariffplan = tariffplan

    @property
    def tariffplanvariant(self) -> int:
        """Gets the tariffplanvariant of this RequestGetFinanciero.


        :return: The tariffplanvariant of this RequestGetFinanciero.
        :rtype: int
        """
        return self._tariffplanvariant

    @tariffplanvariant.setter
    def tariffplanvariant(self, tariffplanvariant: int):
        """Sets the tariffplanvariant of this RequestGetFinanciero.


        :param tariffplanvariant: The tariffplanvariant of this RequestGetFinanciero.
        :type tariffplanvariant: int
        """

        self._tariffplanvariant = tariffplanvariant
