# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.response_get_modos_pago_mpagos import ResponseGetModosPagoMPAGOS  # noqa: F401,E501
from swagger_server import util


class ResponseGetModosPago(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, error_code: int=None, mpagos: List[ResponseGetModosPagoMPAGOS]=None, internal_transaction_id: int=None, external_transaction_id: int=None, message: str=None):  # noqa: E501
        """ResponseGetModosPago - a model defined in Swagger

        :param error_code: The error_code of this ResponseGetModosPago.  # noqa: E501
        :type error_code: int
        :param mpagos: The mpagos of this ResponseGetModosPago.  # noqa: E501
        :type mpagos: List[ResponseGetModosPagoMPAGOS]
        :param internal_transaction_id: The internal_transaction_id of this ResponseGetModosPago.  # noqa: E501
        :type internal_transaction_id: int
        :param external_transaction_id: The external_transaction_id of this ResponseGetModosPago.  # noqa: E501
        :type external_transaction_id: int
        :param message: The message of this ResponseGetModosPago.  # noqa: E501
        :type message: str
        """
        self.swagger_types = {
            'error_code': int,
            'mpagos': List[ResponseGetModosPagoMPAGOS],
            'internal_transaction_id': int,
            'external_transaction_id': int,
            'message': str
        }

        self.attribute_map = {
            'error_code': 'errorCode',
            'mpagos': 'MPAGOS',
            'internal_transaction_id': 'internalTransactionId',
            'external_transaction_id': 'externalTransactionId',
            'message': 'message'
        }
        self._error_code = error_code
        self._mpagos = mpagos
        self._internal_transaction_id = internal_transaction_id
        self._external_transaction_id = external_transaction_id
        self._message = message

    @classmethod
    def from_dict(cls, dikt) -> 'ResponseGetModosPago':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ResponseGetModos_Pago of this ResponseGetModosPago.  # noqa: E501
        :rtype: ResponseGetModosPago
        """
        return util.deserialize_model(dikt, cls)

    @property
    def error_code(self) -> int:
        """Gets the error_code of this ResponseGetModosPago.


        :return: The error_code of this ResponseGetModosPago.
        :rtype: int
        """
        return self._error_code

    @error_code.setter
    def error_code(self, error_code: int):
        """Sets the error_code of this ResponseGetModosPago.


        :param error_code: The error_code of this ResponseGetModosPago.
        :type error_code: int
        """

        self._error_code = error_code

    @property
    def mpagos(self) -> List[ResponseGetModosPagoMPAGOS]:
        """Gets the mpagos of this ResponseGetModosPago.


        :return: The mpagos of this ResponseGetModosPago.
        :rtype: List[ResponseGetModosPagoMPAGOS]
        """
        return self._mpagos

    @mpagos.setter
    def mpagos(self, mpagos: List[ResponseGetModosPagoMPAGOS]):
        """Sets the mpagos of this ResponseGetModosPago.


        :param mpagos: The mpagos of this ResponseGetModosPago.
        :type mpagos: List[ResponseGetModosPagoMPAGOS]
        """

        self._mpagos = mpagos

    @property
    def internal_transaction_id(self) -> int:
        """Gets the internal_transaction_id of this ResponseGetModosPago.


        :return: The internal_transaction_id of this ResponseGetModosPago.
        :rtype: int
        """
        return self._internal_transaction_id

    @internal_transaction_id.setter
    def internal_transaction_id(self, internal_transaction_id: int):
        """Sets the internal_transaction_id of this ResponseGetModosPago.


        :param internal_transaction_id: The internal_transaction_id of this ResponseGetModosPago.
        :type internal_transaction_id: int
        """

        self._internal_transaction_id = internal_transaction_id

    @property
    def external_transaction_id(self) -> int:
        """Gets the external_transaction_id of this ResponseGetModosPago.


        :return: The external_transaction_id of this ResponseGetModosPago.
        :rtype: int
        """
        return self._external_transaction_id

    @external_transaction_id.setter
    def external_transaction_id(self, external_transaction_id: int):
        """Sets the external_transaction_id of this ResponseGetModosPago.


        :param external_transaction_id: The external_transaction_id of this ResponseGetModosPago.
        :type external_transaction_id: int
        """

        self._external_transaction_id = external_transaction_id

    @property
    def message(self) -> str:
        """Gets the message of this ResponseGetModosPago.


        :return: The message of this ResponseGetModosPago.
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message: str):
        """Sets the message of this ResponseGetModosPago.


        :param message: The message of this ResponseGetModosPago.
        :type message: str
        """

        self._message = message
