# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.response_get_servicio_servicios import ResponseGetServicioSERVICIOS  # noqa: F401,E501
from swagger_server import util


class ResponseGetServicio(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, error_code: int=None, servicios: List[ResponseGetServicioSERVICIOS]=None, internal_transaction_id: int=None, external_transaction_id: int=None, message: str=None):  # noqa: E501
        """ResponseGetServicio - a model defined in Swagger

        :param error_code: The error_code of this ResponseGetServicio.  # noqa: E501
        :type error_code: int
        :param servicios: The servicios of this ResponseGetServicio.  # noqa: E501
        :type servicios: List[ResponseGetServicioSERVICIOS]
        :param internal_transaction_id: The internal_transaction_id of this ResponseGetServicio.  # noqa: E501
        :type internal_transaction_id: int
        :param external_transaction_id: The external_transaction_id of this ResponseGetServicio.  # noqa: E501
        :type external_transaction_id: int
        :param message: The message of this ResponseGetServicio.  # noqa: E501
        :type message: str
        """
        self.swagger_types = {
            'error_code': int,
            'servicios': List[ResponseGetServicioSERVICIOS],
            'internal_transaction_id': int,
            'external_transaction_id': int,
            'message': str
        }

        self.attribute_map = {
            'error_code': 'errorCode',
            'servicios': 'SERVICIOS',
            'internal_transaction_id': 'internalTransactionId',
            'external_transaction_id': 'externalTransactionId',
            'message': 'message'
        }
        self._error_code = error_code
        self._servicios = servicios
        self._internal_transaction_id = internal_transaction_id
        self._external_transaction_id = external_transaction_id
        self._message = message

    @classmethod
    def from_dict(cls, dikt) -> 'ResponseGetServicio':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ResponseGetServicio of this ResponseGetServicio.  # noqa: E501
        :rtype: ResponseGetServicio
        """
        return util.deserialize_model(dikt, cls)

    @property
    def error_code(self) -> int:
        """Gets the error_code of this ResponseGetServicio.


        :return: The error_code of this ResponseGetServicio.
        :rtype: int
        """
        return self._error_code

    @error_code.setter
    def error_code(self, error_code: int):
        """Sets the error_code of this ResponseGetServicio.


        :param error_code: The error_code of this ResponseGetServicio.
        :type error_code: int
        """

        self._error_code = error_code

    @property
    def servicios(self) -> List[ResponseGetServicioSERVICIOS]:
        """Gets the servicios of this ResponseGetServicio.


        :return: The servicios of this ResponseGetServicio.
        :rtype: List[ResponseGetServicioSERVICIOS]
        """
        return self._servicios

    @servicios.setter
    def servicios(self, servicios: List[ResponseGetServicioSERVICIOS]):
        """Sets the servicios of this ResponseGetServicio.


        :param servicios: The servicios of this ResponseGetServicio.
        :type servicios: List[ResponseGetServicioSERVICIOS]
        """

        self._servicios = servicios

    @property
    def internal_transaction_id(self) -> int:
        """Gets the internal_transaction_id of this ResponseGetServicio.


        :return: The internal_transaction_id of this ResponseGetServicio.
        :rtype: int
        """
        return self._internal_transaction_id

    @internal_transaction_id.setter
    def internal_transaction_id(self, internal_transaction_id: int):
        """Sets the internal_transaction_id of this ResponseGetServicio.


        :param internal_transaction_id: The internal_transaction_id of this ResponseGetServicio.
        :type internal_transaction_id: int
        """

        self._internal_transaction_id = internal_transaction_id

    @property
    def external_transaction_id(self) -> int:
        """Gets the external_transaction_id of this ResponseGetServicio.


        :return: The external_transaction_id of this ResponseGetServicio.
        :rtype: int
        """
        return self._external_transaction_id

    @external_transaction_id.setter
    def external_transaction_id(self, external_transaction_id: int):
        """Sets the external_transaction_id of this ResponseGetServicio.


        :param external_transaction_id: The external_transaction_id of this ResponseGetServicio.
        :type external_transaction_id: int
        """

        self._external_transaction_id = external_transaction_id

    @property
    def message(self) -> str:
        """Gets the message of this ResponseGetServicio.


        :return: The message of this ResponseGetServicio.
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message: str):
        """Sets the message of this ResponseGetServicio.


        :param message: The message of this ResponseGetServicio.
        :type message: str
        """

        self._message = message
