# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.response_get_provincias_provincies import ResponseGetProvinciasPROVINCIES  # noqa: F401,E501
from swagger_server import util


class ResponseGetProvincias(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, error_code: int=None, provincies: List[ResponseGetProvinciasPROVINCIES]=None, internal_transaction_id: int=None, external_transaction_id: int=None, message: str=None):  # noqa: E501
        """ResponseGetProvincias - a model defined in Swagger

        :param error_code: The error_code of this ResponseGetProvincias.  # noqa: E501
        :type error_code: int
        :param provincies: The provincies of this ResponseGetProvincias.  # noqa: E501
        :type provincies: List[ResponseGetProvinciasPROVINCIES]
        :param internal_transaction_id: The internal_transaction_id of this ResponseGetProvincias.  # noqa: E501
        :type internal_transaction_id: int
        :param external_transaction_id: The external_transaction_id of this ResponseGetProvincias.  # noqa: E501
        :type external_transaction_id: int
        :param message: The message of this ResponseGetProvincias.  # noqa: E501
        :type message: str
        """
        self.swagger_types = {
            'error_code': int,
            'provincies': List[ResponseGetProvinciasPROVINCIES],
            'internal_transaction_id': int,
            'external_transaction_id': int,
            'message': str
        }

        self.attribute_map = {
            'error_code': 'errorCode',
            'provincies': 'PROVINCIES',
            'internal_transaction_id': 'internalTransactionId',
            'external_transaction_id': 'externalTransactionId',
            'message': 'message'
        }
        self._error_code = error_code
        self._provincies = provincies
        self._internal_transaction_id = internal_transaction_id
        self._external_transaction_id = external_transaction_id
        self._message = message

    @classmethod
    def from_dict(cls, dikt) -> 'ResponseGetProvincias':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ResponseGetProvincias of this ResponseGetProvincias.  # noqa: E501
        :rtype: ResponseGetProvincias
        """
        return util.deserialize_model(dikt, cls)

    @property
    def error_code(self) -> int:
        """Gets the error_code of this ResponseGetProvincias.


        :return: The error_code of this ResponseGetProvincias.
        :rtype: int
        """
        return self._error_code

    @error_code.setter
    def error_code(self, error_code: int):
        """Sets the error_code of this ResponseGetProvincias.


        :param error_code: The error_code of this ResponseGetProvincias.
        :type error_code: int
        """

        self._error_code = error_code

    @property
    def provincies(self) -> List[ResponseGetProvinciasPROVINCIES]:
        """Gets the provincies of this ResponseGetProvincias.


        :return: The provincies of this ResponseGetProvincias.
        :rtype: List[ResponseGetProvinciasPROVINCIES]
        """
        return self._provincies

    @provincies.setter
    def provincies(self, provincies: List[ResponseGetProvinciasPROVINCIES]):
        """Sets the provincies of this ResponseGetProvincias.


        :param provincies: The provincies of this ResponseGetProvincias.
        :type provincies: List[ResponseGetProvinciasPROVINCIES]
        """

        self._provincies = provincies

    @property
    def internal_transaction_id(self) -> int:
        """Gets the internal_transaction_id of this ResponseGetProvincias.


        :return: The internal_transaction_id of this ResponseGetProvincias.
        :rtype: int
        """
        return self._internal_transaction_id

    @internal_transaction_id.setter
    def internal_transaction_id(self, internal_transaction_id: int):
        """Sets the internal_transaction_id of this ResponseGetProvincias.


        :param internal_transaction_id: The internal_transaction_id of this ResponseGetProvincias.
        :type internal_transaction_id: int
        """

        self._internal_transaction_id = internal_transaction_id

    @property
    def external_transaction_id(self) -> int:
        """Gets the external_transaction_id of this ResponseGetProvincias.


        :return: The external_transaction_id of this ResponseGetProvincias.
        :rtype: int
        """
        return self._external_transaction_id

    @external_transaction_id.setter
    def external_transaction_id(self, external_transaction_id: int):
        """Sets the external_transaction_id of this ResponseGetProvincias.


        :param external_transaction_id: The external_transaction_id of this ResponseGetProvincias.
        :type external_transaction_id: int
        """

        self._external_transaction_id = external_transaction_id

    @property
    def message(self) -> str:
        """Gets the message of this ResponseGetProvincias.


        :return: The message of this ResponseGetProvincias.
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message: str):
        """Sets the message of this ResponseGetProvincias.


        :param message: The message of this ResponseGetProvincias.
        :type message: str
        """

        self._message = message
