# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.response_get_combo_plan_variant_comboplanvariant import ResponseGetComboPlanVariantCOMBOPLANVARIANT  # noqa: F401,E501
from swagger_server import util


class ResponseGetComboPlanVariant(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, error_code: int=None, combo_planvariant: List[ResponseGetComboPlanVariantCOMBOPLANVARIANT]=None, internal_transaction_id: int=None, external_transaction_id: int=None, message: str=None):  # noqa: E501
        """ResponseGetComboPlanVariant - a model defined in Swagger

        :param error_code: The error_code of this ResponseGetComboPlanVariant.  # noqa: E501
        :type error_code: int
        :param combo_planvariant: The combo_planvariant of this ResponseGetComboPlanVariant.  # noqa: E501
        :type combo_planvariant: List[ResponseGetComboPlanVariantCOMBOPLANVARIANT]
        :param internal_transaction_id: The internal_transaction_id of this ResponseGetComboPlanVariant.  # noqa: E501
        :type internal_transaction_id: int
        :param external_transaction_id: The external_transaction_id of this ResponseGetComboPlanVariant.  # noqa: E501
        :type external_transaction_id: int
        :param message: The message of this ResponseGetComboPlanVariant.  # noqa: E501
        :type message: str
        """
        self.swagger_types = {
            'error_code': int,
            'combo_planvariant': List[ResponseGetComboPlanVariantCOMBOPLANVARIANT],
            'internal_transaction_id': int,
            'external_transaction_id': int,
            'message': str
        }

        self.attribute_map = {
            'error_code': 'errorCode',
            'combo_planvariant': 'COMBO_PLANVARIANT',
            'internal_transaction_id': 'internalTransactionId',
            'external_transaction_id': 'externalTransactionId',
            'message': 'message'
        }
        self._error_code = error_code
        self._combo_planvariant = combo_planvariant
        self._internal_transaction_id = internal_transaction_id
        self._external_transaction_id = external_transaction_id
        self._message = message

    @classmethod
    def from_dict(cls, dikt) -> 'ResponseGetComboPlanVariant':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ResponseGetCombo_PlanVariant of this ResponseGetComboPlanVariant.  # noqa: E501
        :rtype: ResponseGetComboPlanVariant
        """
        return util.deserialize_model(dikt, cls)

    @property
    def error_code(self) -> int:
        """Gets the error_code of this ResponseGetComboPlanVariant.


        :return: The error_code of this ResponseGetComboPlanVariant.
        :rtype: int
        """
        return self._error_code

    @error_code.setter
    def error_code(self, error_code: int):
        """Sets the error_code of this ResponseGetComboPlanVariant.


        :param error_code: The error_code of this ResponseGetComboPlanVariant.
        :type error_code: int
        """

        self._error_code = error_code

    @property
    def combo_planvariant(self) -> List[ResponseGetComboPlanVariantCOMBOPLANVARIANT]:
        """Gets the combo_planvariant of this ResponseGetComboPlanVariant.


        :return: The combo_planvariant of this ResponseGetComboPlanVariant.
        :rtype: List[ResponseGetComboPlanVariantCOMBOPLANVARIANT]
        """
        return self._combo_planvariant

    @combo_planvariant.setter
    def combo_planvariant(self, combo_planvariant: List[ResponseGetComboPlanVariantCOMBOPLANVARIANT]):
        """Sets the combo_planvariant of this ResponseGetComboPlanVariant.


        :param combo_planvariant: The combo_planvariant of this ResponseGetComboPlanVariant.
        :type combo_planvariant: List[ResponseGetComboPlanVariantCOMBOPLANVARIANT]
        """

        self._combo_planvariant = combo_planvariant

    @property
    def internal_transaction_id(self) -> int:
        """Gets the internal_transaction_id of this ResponseGetComboPlanVariant.


        :return: The internal_transaction_id of this ResponseGetComboPlanVariant.
        :rtype: int
        """
        return self._internal_transaction_id

    @internal_transaction_id.setter
    def internal_transaction_id(self, internal_transaction_id: int):
        """Sets the internal_transaction_id of this ResponseGetComboPlanVariant.


        :param internal_transaction_id: The internal_transaction_id of this ResponseGetComboPlanVariant.
        :type internal_transaction_id: int
        """

        self._internal_transaction_id = internal_transaction_id

    @property
    def external_transaction_id(self) -> int:
        """Gets the external_transaction_id of this ResponseGetComboPlanVariant.


        :return: The external_transaction_id of this ResponseGetComboPlanVariant.
        :rtype: int
        """
        return self._external_transaction_id

    @external_transaction_id.setter
    def external_transaction_id(self, external_transaction_id: int):
        """Sets the external_transaction_id of this ResponseGetComboPlanVariant.


        :param external_transaction_id: The external_transaction_id of this ResponseGetComboPlanVariant.
        :type external_transaction_id: int
        """

        self._external_transaction_id = external_transaction_id

    @property
    def message(self) -> str:
        """Gets the message of this ResponseGetComboPlanVariant.


        :return: The message of this ResponseGetComboPlanVariant.
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message: str):
        """Sets the message of this ResponseGetComboPlanVariant.


        :param message: The message of this ResponseGetComboPlanVariant.
        :type message: str
        """

        self._message = message
