# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class ResponseGetComboProductoCOMBOPRODUCTO(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, producto: str=None, productid: int=None):  # noqa: E501
        """ResponseGetComboProductoCOMBOPRODUCTO - a model defined in Swagger

        :param producto: The producto of this ResponseGetComboProductoCOMBOPRODUCTO.  # noqa: E501
        :type producto: str
        :param productid: The productid of this ResponseGetComboProductoCOMBOPRODUCTO.  # noqa: E501
        :type productid: int
        """
        self.swagger_types = {
            'producto': str,
            'productid': int
        }

        self.attribute_map = {
            'producto': 'PRODUCTO',
            'productid': 'PRODUCTID'
        }
        self._producto = producto
        self._productid = productid

    @classmethod
    def from_dict(cls, dikt) -> 'ResponseGetComboProductoCOMBOPRODUCTO':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ResponseGetCombo_Producto_COMBO_PRODUCTO of this ResponseGetComboProductoCOMBOPRODUCTO.  # noqa: E501
        :rtype: ResponseGetComboProductoCOMBOPRODUCTO
        """
        return util.deserialize_model(dikt, cls)

    @property
    def producto(self) -> str:
        """Gets the producto of this ResponseGetComboProductoCOMBOPRODUCTO.


        :return: The producto of this ResponseGetComboProductoCOMBOPRODUCTO.
        :rtype: str
        """
        return self._producto

    @producto.setter
    def producto(self, producto: str):
        """Sets the producto of this ResponseGetComboProductoCOMBOPRODUCTO.


        :param producto: The producto of this ResponseGetComboProductoCOMBOPRODUCTO.
        :type producto: str
        """

        self._producto = producto

    @property
    def productid(self) -> int:
        """Gets the productid of this ResponseGetComboProductoCOMBOPRODUCTO.


        :return: The productid of this ResponseGetComboProductoCOMBOPRODUCTO.
        :rtype: int
        """
        return self._productid

    @productid.setter
    def productid(self, productid: int):
        """Sets the productid of this ResponseGetComboProductoCOMBOPRODUCTO.


        :param productid: The productid of this ResponseGetComboProductoCOMBOPRODUCTO.
        :type productid: int
        """

        self._productid = productid
