# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.response_get_buro_buro import ResponseGetBuroBURO  # noqa: F401,E501
from swagger_server import util


class ResponseGetBuro(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, error_code: int=None, buro: List[ResponseGetBuroBURO]=None, internal_transaction_id: int=None, external_transaction_id: int=None, message: str=None):  # noqa: E501
        """ResponseGetBuro - a model defined in Swagger

        :param error_code: The error_code of this ResponseGetBuro.  # noqa: E501
        :type error_code: int
        :param buro: The buro of this ResponseGetBuro.  # noqa: E501
        :type buro: List[ResponseGetBuroBURO]
        :param internal_transaction_id: The internal_transaction_id of this ResponseGetBuro.  # noqa: E501
        :type internal_transaction_id: int
        :param external_transaction_id: The external_transaction_id of this ResponseGetBuro.  # noqa: E501
        :type external_transaction_id: int
        :param message: The message of this ResponseGetBuro.  # noqa: E501
        :type message: str
        """
        self.swagger_types = {
            'error_code': int,
            'buro': List[ResponseGetBuroBURO],
            'internal_transaction_id': int,
            'external_transaction_id': int,
            'message': str
        }

        self.attribute_map = {
            'error_code': 'errorCode',
            'buro': 'BURO',
            'internal_transaction_id': 'internalTransactionId',
            'external_transaction_id': 'externalTransactionId',
            'message': 'message'
        }
        self._error_code = error_code
        self._buro = buro
        self._internal_transaction_id = internal_transaction_id
        self._external_transaction_id = external_transaction_id
        self._message = message

    @classmethod
    def from_dict(cls, dikt) -> 'ResponseGetBuro':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ResponseGetBuro of this ResponseGetBuro.  # noqa: E501
        :rtype: ResponseGetBuro
        """
        return util.deserialize_model(dikt, cls)

    @property
    def error_code(self) -> int:
        """Gets the error_code of this ResponseGetBuro.


        :return: The error_code of this ResponseGetBuro.
        :rtype: int
        """
        return self._error_code

    @error_code.setter
    def error_code(self, error_code: int):
        """Sets the error_code of this ResponseGetBuro.


        :param error_code: The error_code of this ResponseGetBuro.
        :type error_code: int
        """

        self._error_code = error_code

    @property
    def buro(self) -> List[ResponseGetBuroBURO]:
        """Gets the buro of this ResponseGetBuro.


        :return: The buro of this ResponseGetBuro.
        :rtype: List[ResponseGetBuroBURO]
        """
        return self._buro

    @buro.setter
    def buro(self, buro: List[ResponseGetBuroBURO]):
        """Sets the buro of this ResponseGetBuro.


        :param buro: The buro of this ResponseGetBuro.
        :type buro: List[ResponseGetBuroBURO]
        """

        self._buro = buro

    @property
    def internal_transaction_id(self) -> int:
        """Gets the internal_transaction_id of this ResponseGetBuro.


        :return: The internal_transaction_id of this ResponseGetBuro.
        :rtype: int
        """
        return self._internal_transaction_id

    @internal_transaction_id.setter
    def internal_transaction_id(self, internal_transaction_id: int):
        """Sets the internal_transaction_id of this ResponseGetBuro.


        :param internal_transaction_id: The internal_transaction_id of this ResponseGetBuro.
        :type internal_transaction_id: int
        """

        self._internal_transaction_id = internal_transaction_id

    @property
    def external_transaction_id(self) -> int:
        """Gets the external_transaction_id of this ResponseGetBuro.


        :return: The external_transaction_id of this ResponseGetBuro.
        :rtype: int
        """
        return self._external_transaction_id

    @external_transaction_id.setter
    def external_transaction_id(self, external_transaction_id: int):
        """Sets the external_transaction_id of this ResponseGetBuro.


        :param external_transaction_id: The external_transaction_id of this ResponseGetBuro.
        :type external_transaction_id: int
        """

        self._external_transaction_id = external_transaction_id

    @property
    def message(self) -> str:
        """Gets the message of this ResponseGetBuro.


        :return: The message of this ResponseGetBuro.
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message: str):
        """Sets the message of this ResponseGetBuro.


        :param message: The message of this ResponseGetBuro.
        :type message: str
        """

        self._message = message
