# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.response_get_tecnologias_tecnologias import ResponseGetTecnologiasTECNOLOGIAS  # noqa: F401,E501
from swagger_server import util


class ResponseGetTecnologias(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, error_code: int=None, tecnologias: List[ResponseGetTecnologiasTECNOLOGIAS]=None, internal_transaction_id: int=None, external_transaction_id: int=None, message: str=None):  # noqa: E501
        """ResponseGetTecnologias - a model defined in Swagger

        :param error_code: The error_code of this ResponseGetTecnologias.  # noqa: E501
        :type error_code: int
        :param tecnologias: The tecnologias of this ResponseGetTecnologias.  # noqa: E501
        :type tecnologias: List[ResponseGetTecnologiasTECNOLOGIAS]
        :param internal_transaction_id: The internal_transaction_id of this ResponseGetTecnologias.  # noqa: E501
        :type internal_transaction_id: int
        :param external_transaction_id: The external_transaction_id of this ResponseGetTecnologias.  # noqa: E501
        :type external_transaction_id: int
        :param message: The message of this ResponseGetTecnologias.  # noqa: E501
        :type message: str
        """
        self.swagger_types = {
            'error_code': int,
            'tecnologias': List[ResponseGetTecnologiasTECNOLOGIAS],
            'internal_transaction_id': int,
            'external_transaction_id': int,
            'message': str
        }

        self.attribute_map = {
            'error_code': 'errorCode',
            'tecnologias': 'TECNOLOGIAS',
            'internal_transaction_id': 'internalTransactionId',
            'external_transaction_id': 'externalTransactionId',
            'message': 'message'
        }
        self._error_code = error_code
        self._tecnologias = tecnologias
        self._internal_transaction_id = internal_transaction_id
        self._external_transaction_id = external_transaction_id
        self._message = message

    @classmethod
    def from_dict(cls, dikt) -> 'ResponseGetTecnologias':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ResponseGetTecnologias of this ResponseGetTecnologias.  # noqa: E501
        :rtype: ResponseGetTecnologias
        """
        return util.deserialize_model(dikt, cls)

    @property
    def error_code(self) -> int:
        """Gets the error_code of this ResponseGetTecnologias.


        :return: The error_code of this ResponseGetTecnologias.
        :rtype: int
        """
        return self._error_code

    @error_code.setter
    def error_code(self, error_code: int):
        """Sets the error_code of this ResponseGetTecnologias.


        :param error_code: The error_code of this ResponseGetTecnologias.
        :type error_code: int
        """

        self._error_code = error_code

    @property
    def tecnologias(self) -> List[ResponseGetTecnologiasTECNOLOGIAS]:
        """Gets the tecnologias of this ResponseGetTecnologias.


        :return: The tecnologias of this ResponseGetTecnologias.
        :rtype: List[ResponseGetTecnologiasTECNOLOGIAS]
        """
        return self._tecnologias

    @tecnologias.setter
    def tecnologias(self, tecnologias: List[ResponseGetTecnologiasTECNOLOGIAS]):
        """Sets the tecnologias of this ResponseGetTecnologias.


        :param tecnologias: The tecnologias of this ResponseGetTecnologias.
        :type tecnologias: List[ResponseGetTecnologiasTECNOLOGIAS]
        """

        self._tecnologias = tecnologias

    @property
    def internal_transaction_id(self) -> int:
        """Gets the internal_transaction_id of this ResponseGetTecnologias.


        :return: The internal_transaction_id of this ResponseGetTecnologias.
        :rtype: int
        """
        return self._internal_transaction_id

    @internal_transaction_id.setter
    def internal_transaction_id(self, internal_transaction_id: int):
        """Sets the internal_transaction_id of this ResponseGetTecnologias.


        :param internal_transaction_id: The internal_transaction_id of this ResponseGetTecnologias.
        :type internal_transaction_id: int
        """

        self._internal_transaction_id = internal_transaction_id

    @property
    def external_transaction_id(self) -> int:
        """Gets the external_transaction_id of this ResponseGetTecnologias.


        :return: The external_transaction_id of this ResponseGetTecnologias.
        :rtype: int
        """
        return self._external_transaction_id

    @external_transaction_id.setter
    def external_transaction_id(self, external_transaction_id: int):
        """Sets the external_transaction_id of this ResponseGetTecnologias.


        :param external_transaction_id: The external_transaction_id of this ResponseGetTecnologias.
        :type external_transaction_id: int
        """

        self._external_transaction_id = external_transaction_id

    @property
    def message(self) -> str:
        """Gets the message of this ResponseGetTecnologias.


        :return: The message of this ResponseGetTecnologias.
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message: str):
        """Sets the message of this ResponseGetTecnologias.


        :param message: The message of this ResponseGetTecnologias.
        :type message: str
        """

        self._message = message
