# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.response_get_ofertas_ofertas import ResponseGetOfertasOFERTAS  # noqa: F401,E501
from swagger_server import util


class ResponseGetOfertas(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, error_code: int=None, ofertas: List[ResponseGetOfertasOFERTAS]=None, internal_transaction_id: int=None, external_transaction_id: int=None, message: str=None):  # noqa: E501
        """ResponseGetOfertas - a model defined in Swagger

        :param error_code: The error_code of this ResponseGetOfertas.  # noqa: E501
        :type error_code: int
        :param ofertas: The ofertas of this ResponseGetOfertas.  # noqa: E501
        :type ofertas: List[ResponseGetOfertasOFERTAS]
        :param internal_transaction_id: The internal_transaction_id of this ResponseGetOfertas.  # noqa: E501
        :type internal_transaction_id: int
        :param external_transaction_id: The external_transaction_id of this ResponseGetOfertas.  # noqa: E501
        :type external_transaction_id: int
        :param message: The message of this ResponseGetOfertas.  # noqa: E501
        :type message: str
        """
        self.swagger_types = {
            'error_code': int,
            'ofertas': List[ResponseGetOfertasOFERTAS],
            'internal_transaction_id': int,
            'external_transaction_id': int,
            'message': str
        }

        self.attribute_map = {
            'error_code': 'errorCode',
            'ofertas': 'OFERTAS',
            'internal_transaction_id': 'internalTransactionId',
            'external_transaction_id': 'externalTransactionId',
            'message': 'message'
        }
        self._error_code = error_code
        self._ofertas = ofertas
        self._internal_transaction_id = internal_transaction_id
        self._external_transaction_id = external_transaction_id
        self._message = message

    @classmethod
    def from_dict(cls, dikt) -> 'ResponseGetOfertas':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ResponseGetOfertas of this ResponseGetOfertas.  # noqa: E501
        :rtype: ResponseGetOfertas
        """
        return util.deserialize_model(dikt, cls)

    @property
    def error_code(self) -> int:
        """Gets the error_code of this ResponseGetOfertas.


        :return: The error_code of this ResponseGetOfertas.
        :rtype: int
        """
        return self._error_code

    @error_code.setter
    def error_code(self, error_code: int):
        """Sets the error_code of this ResponseGetOfertas.


        :param error_code: The error_code of this ResponseGetOfertas.
        :type error_code: int
        """

        self._error_code = error_code

    @property
    def ofertas(self) -> List[ResponseGetOfertasOFERTAS]:
        """Gets the ofertas of this ResponseGetOfertas.


        :return: The ofertas of this ResponseGetOfertas.
        :rtype: List[ResponseGetOfertasOFERTAS]
        """
        return self._ofertas

    @ofertas.setter
    def ofertas(self, ofertas: List[ResponseGetOfertasOFERTAS]):
        """Sets the ofertas of this ResponseGetOfertas.


        :param ofertas: The ofertas of this ResponseGetOfertas.
        :type ofertas: List[ResponseGetOfertasOFERTAS]
        """

        self._ofertas = ofertas

    @property
    def internal_transaction_id(self) -> int:
        """Gets the internal_transaction_id of this ResponseGetOfertas.


        :return: The internal_transaction_id of this ResponseGetOfertas.
        :rtype: int
        """
        return self._internal_transaction_id

    @internal_transaction_id.setter
    def internal_transaction_id(self, internal_transaction_id: int):
        """Sets the internal_transaction_id of this ResponseGetOfertas.


        :param internal_transaction_id: The internal_transaction_id of this ResponseGetOfertas.
        :type internal_transaction_id: int
        """

        self._internal_transaction_id = internal_transaction_id

    @property
    def external_transaction_id(self) -> int:
        """Gets the external_transaction_id of this ResponseGetOfertas.


        :return: The external_transaction_id of this ResponseGetOfertas.
        :rtype: int
        """
        return self._external_transaction_id

    @external_transaction_id.setter
    def external_transaction_id(self, external_transaction_id: int):
        """Sets the external_transaction_id of this ResponseGetOfertas.


        :param external_transaction_id: The external_transaction_id of this ResponseGetOfertas.
        :type external_transaction_id: int
        """

        self._external_transaction_id = external_transaction_id

    @property
    def message(self) -> str:
        """Gets the message of this ResponseGetOfertas.


        :return: The message of this ResponseGetOfertas.
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message: str):
        """Sets the message of this ResponseGetOfertas.


        :param message: The message of this ResponseGetOfertas.
        :type message: str
        """

        self._message = message
