# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class ResponseGetServicioSERVICIOS(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, servicios: str=None):  # noqa: E501
        """ResponseGetServicioSERVICIOS - a model defined in Swagger

        :param servicios: The servicios of this ResponseGetServicioSERVICIOS.  # noqa: E501
        :type servicios: str
        """
        self.swagger_types = {
            'servicios': str
        }

        self.attribute_map = {
            'servicios': 'SERVICIOS'
        }
        self._servicios = servicios

    @classmethod
    def from_dict(cls, dikt) -> 'ResponseGetServicioSERVICIOS':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ResponseGetServicio_SERVICIOS of this ResponseGetServicioSERVICIOS.  # noqa: E501
        :rtype: ResponseGetServicioSERVICIOS
        """
        return util.deserialize_model(dikt, cls)

    @property
    def servicios(self) -> str:
        """Gets the servicios of this ResponseGetServicioSERVICIOS.


        :return: The servicios of this ResponseGetServicioSERVICIOS.
        :rtype: str
        """
        return self._servicios

    @servicios.setter
    def servicios(self, servicios: str):
        """Sets the servicios of this ResponseGetServicioSERVICIOS.


        :param servicios: The servicios of this ResponseGetServicioSERVICIOS.
        :type servicios: str
        """

        self._servicios = servicios
