# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.response_get_precio_regular_precioregular import ResponseGetPrecioRegularPRECIOREGULAR  # noqa: F401,E501
from swagger_server import util


class ResponseGetPrecioRegular(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, error_code: int=None, precio_regular: List[ResponseGetPrecioRegularPRECIOREGULAR]=None, internal_transaction_id: int=None, external_transaction_id: int=None, message: str=None):  # noqa: E501
        """ResponseGetPrecioRegular - a model defined in Swagger

        :param error_code: The error_code of this ResponseGetPrecioRegular.  # noqa: E501
        :type error_code: int
        :param precio_regular: The precio_regular of this ResponseGetPrecioRegular.  # noqa: E501
        :type precio_regular: List[ResponseGetPrecioRegularPRECIOREGULAR]
        :param internal_transaction_id: The internal_transaction_id of this ResponseGetPrecioRegular.  # noqa: E501
        :type internal_transaction_id: int
        :param external_transaction_id: The external_transaction_id of this ResponseGetPrecioRegular.  # noqa: E501
        :type external_transaction_id: int
        :param message: The message of this ResponseGetPrecioRegular.  # noqa: E501
        :type message: str
        """
        self.swagger_types = {
            'error_code': int,
            'precio_regular': List[ResponseGetPrecioRegularPRECIOREGULAR],
            'internal_transaction_id': int,
            'external_transaction_id': int,
            'message': str
        }

        self.attribute_map = {
            'error_code': 'errorCode',
            'precio_regular': 'PRECIO_REGULAR',
            'internal_transaction_id': 'internalTransactionId',
            'external_transaction_id': 'externalTransactionId',
            'message': 'message'
        }
        self._error_code = error_code
        self._precio_regular = precio_regular
        self._internal_transaction_id = internal_transaction_id
        self._external_transaction_id = external_transaction_id
        self._message = message

    @classmethod
    def from_dict(cls, dikt) -> 'ResponseGetPrecioRegular':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ResponseGetPrecio_Regular of this ResponseGetPrecioRegular.  # noqa: E501
        :rtype: ResponseGetPrecioRegular
        """
        return util.deserialize_model(dikt, cls)

    @property
    def error_code(self) -> int:
        """Gets the error_code of this ResponseGetPrecioRegular.


        :return: The error_code of this ResponseGetPrecioRegular.
        :rtype: int
        """
        return self._error_code

    @error_code.setter
    def error_code(self, error_code: int):
        """Sets the error_code of this ResponseGetPrecioRegular.


        :param error_code: The error_code of this ResponseGetPrecioRegular.
        :type error_code: int
        """

        self._error_code = error_code

    @property
    def precio_regular(self) -> List[ResponseGetPrecioRegularPRECIOREGULAR]:
        """Gets the precio_regular of this ResponseGetPrecioRegular.


        :return: The precio_regular of this ResponseGetPrecioRegular.
        :rtype: List[ResponseGetPrecioRegularPRECIOREGULAR]
        """
        return self._precio_regular

    @precio_regular.setter
    def precio_regular(self, precio_regular: List[ResponseGetPrecioRegularPRECIOREGULAR]):
        """Sets the precio_regular of this ResponseGetPrecioRegular.


        :param precio_regular: The precio_regular of this ResponseGetPrecioRegular.
        :type precio_regular: List[ResponseGetPrecioRegularPRECIOREGULAR]
        """

        self._precio_regular = precio_regular

    @property
    def internal_transaction_id(self) -> int:
        """Gets the internal_transaction_id of this ResponseGetPrecioRegular.


        :return: The internal_transaction_id of this ResponseGetPrecioRegular.
        :rtype: int
        """
        return self._internal_transaction_id

    @internal_transaction_id.setter
    def internal_transaction_id(self, internal_transaction_id: int):
        """Sets the internal_transaction_id of this ResponseGetPrecioRegular.


        :param internal_transaction_id: The internal_transaction_id of this ResponseGetPrecioRegular.
        :type internal_transaction_id: int
        """

        self._internal_transaction_id = internal_transaction_id

    @property
    def external_transaction_id(self) -> int:
        """Gets the external_transaction_id of this ResponseGetPrecioRegular.


        :return: The external_transaction_id of this ResponseGetPrecioRegular.
        :rtype: int
        """
        return self._external_transaction_id

    @external_transaction_id.setter
    def external_transaction_id(self, external_transaction_id: int):
        """Sets the external_transaction_id of this ResponseGetPrecioRegular.


        :param external_transaction_id: The external_transaction_id of this ResponseGetPrecioRegular.
        :type external_transaction_id: int
        """

        self._external_transaction_id = external_transaction_id

    @property
    def message(self) -> str:
        """Gets the message of this ResponseGetPrecioRegular.


        :return: The message of this ResponseGetPrecioRegular.
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message: str):
        """Sets the message of this ResponseGetPrecioRegular.


        :param message: The message of this ResponseGetPrecioRegular.
        :type message: str
        """

        self._message = message
