# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.response_get_sectores_sectors import ResponseGetSectoresSECTORS  # noqa: F401,E501
from swagger_server import util


class ResponseGetSectoresPorCiudad(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, error_code: int=None, sectorsx_city: List[ResponseGetSectoresSECTORS]=None, internal_transaction_id: int=None, external_transaction_id: int=None, message: str=None):  # noqa: E501
        """ResponseGetSectoresPorCiudad - a model defined in Swagger

        :param error_code: The error_code of this ResponseGetSectoresPorCiudad.  # noqa: E501
        :type error_code: int
        :param sectorsx_city: The sectorsx_city of this ResponseGetSectoresPorCiudad.  # noqa: E501
        :type sectorsx_city: List[ResponseGetSectoresSECTORS]
        :param internal_transaction_id: The internal_transaction_id of this ResponseGetSectoresPorCiudad.  # noqa: E501
        :type internal_transaction_id: int
        :param external_transaction_id: The external_transaction_id of this ResponseGetSectoresPorCiudad.  # noqa: E501
        :type external_transaction_id: int
        :param message: The message of this ResponseGetSectoresPorCiudad.  # noqa: E501
        :type message: str
        """
        self.swagger_types = {
            'error_code': int,
            'sectorsx_city': List[ResponseGetSectoresSECTORS],
            'internal_transaction_id': int,
            'external_transaction_id': int,
            'message': str
        }

        self.attribute_map = {
            'error_code': 'errorCode',
            'sectorsx_city': 'SECTORSxCITY',
            'internal_transaction_id': 'internalTransactionId',
            'external_transaction_id': 'externalTransactionId',
            'message': 'message'
        }
        self._error_code = error_code
        self._sectorsx_city = sectorsx_city
        self._internal_transaction_id = internal_transaction_id
        self._external_transaction_id = external_transaction_id
        self._message = message

    @classmethod
    def from_dict(cls, dikt) -> 'ResponseGetSectoresPorCiudad':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ResponseGetSectoresPorCiudad of this ResponseGetSectoresPorCiudad.  # noqa: E501
        :rtype: ResponseGetSectoresPorCiudad
        """
        return util.deserialize_model(dikt, cls)

    @property
    def error_code(self) -> int:
        """Gets the error_code of this ResponseGetSectoresPorCiudad.


        :return: The error_code of this ResponseGetSectoresPorCiudad.
        :rtype: int
        """
        return self._error_code

    @error_code.setter
    def error_code(self, error_code: int):
        """Sets the error_code of this ResponseGetSectoresPorCiudad.


        :param error_code: The error_code of this ResponseGetSectoresPorCiudad.
        :type error_code: int
        """

        self._error_code = error_code

    @property
    def sectorsx_city(self) -> List[ResponseGetSectoresSECTORS]:
        """Gets the sectorsx_city of this ResponseGetSectoresPorCiudad.


        :return: The sectorsx_city of this ResponseGetSectoresPorCiudad.
        :rtype: List[ResponseGetSectoresSECTORS]
        """
        return self._sectorsx_city

    @sectorsx_city.setter
    def sectorsx_city(self, sectorsx_city: List[ResponseGetSectoresSECTORS]):
        """Sets the sectorsx_city of this ResponseGetSectoresPorCiudad.


        :param sectorsx_city: The sectorsx_city of this ResponseGetSectoresPorCiudad.
        :type sectorsx_city: List[ResponseGetSectoresSECTORS]
        """

        self._sectorsx_city = sectorsx_city

    @property
    def internal_transaction_id(self) -> int:
        """Gets the internal_transaction_id of this ResponseGetSectoresPorCiudad.


        :return: The internal_transaction_id of this ResponseGetSectoresPorCiudad.
        :rtype: int
        """
        return self._internal_transaction_id

    @internal_transaction_id.setter
    def internal_transaction_id(self, internal_transaction_id: int):
        """Sets the internal_transaction_id of this ResponseGetSectoresPorCiudad.


        :param internal_transaction_id: The internal_transaction_id of this ResponseGetSectoresPorCiudad.
        :type internal_transaction_id: int
        """

        self._internal_transaction_id = internal_transaction_id

    @property
    def external_transaction_id(self) -> int:
        """Gets the external_transaction_id of this ResponseGetSectoresPorCiudad.


        :return: The external_transaction_id of this ResponseGetSectoresPorCiudad.
        :rtype: int
        """
        return self._external_transaction_id

    @external_transaction_id.setter
    def external_transaction_id(self, external_transaction_id: int):
        """Sets the external_transaction_id of this ResponseGetSectoresPorCiudad.


        :param external_transaction_id: The external_transaction_id of this ResponseGetSectoresPorCiudad.
        :type external_transaction_id: int
        """

        self._external_transaction_id = external_transaction_id

    @property
    def message(self) -> str:
        """Gets the message of this ResponseGetSectoresPorCiudad.


        :return: The message of this ResponseGetSectoresPorCiudad.
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message: str):
        """Sets the message of this ResponseGetSectoresPorCiudad.


        :param message: The message of this ResponseGetSectoresPorCiudad.
        :type message: str
        """

        self._message = message
