# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class ResponseGetTipoServicioTIPOSERVICIO(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, tipo_servicio: str=None):  # noqa: E501
        """ResponseGetTipoServicioTIPOSERVICIO - a model defined in Swagger

        :param tipo_servicio: The tipo_servicio of this ResponseGetTipoServicioTIPOSERVICIO.  # noqa: E501
        :type tipo_servicio: str
        """
        self.swagger_types = {
            'tipo_servicio': str
        }

        self.attribute_map = {
            'tipo_servicio': 'TIPO_SERVICIO'
        }
        self._tipo_servicio = tipo_servicio

    @classmethod
    def from_dict(cls, dikt) -> 'ResponseGetTipoServicioTIPOSERVICIO':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ResponseGetTipo_Servicio_TIPO_SERVICIO of this ResponseGetTipoServicioTIPOSERVICIO.  # noqa: E501
        :rtype: ResponseGetTipoServicioTIPOSERVICIO
        """
        return util.deserialize_model(dikt, cls)

    @property
    def tipo_servicio(self) -> str:
        """Gets the tipo_servicio of this ResponseGetTipoServicioTIPOSERVICIO.


        :return: The tipo_servicio of this ResponseGetTipoServicioTIPOSERVICIO.
        :rtype: str
        """
        return self._tipo_servicio

    @tipo_servicio.setter
    def tipo_servicio(self, tipo_servicio: str):
        """Sets the tipo_servicio of this ResponseGetTipoServicioTIPOSERVICIO.


        :param tipo_servicio: The tipo_servicio of this ResponseGetTipoServicioTIPOSERVICIO.
        :type tipo_servicio: str
        """

        self._tipo_servicio = tipo_servicio
