# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class ResponseGetCiudadesCITIES(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, ciudad: str=None, ciudad_id: int=None, provincia: str=None):  # noqa: E501
        """ResponseGetCiudadesCITIES - a model defined in Swagger

        :param ciudad: The ciudad of this ResponseGetCiudadesCITIES.  # noqa: E501
        :type ciudad: str
        :param ciudad_id: The ciudad_id of this ResponseGetCiudadesCITIES.  # noqa: E501
        :type ciudad_id: int
        :param provincia: The provincia of this ResponseGetCiudadesCITIES.  # noqa: E501
        :type provincia: str
        """
        self.swagger_types = {
            'ciudad': str,
            'ciudad_id': int,
            'provincia': str
        }

        self.attribute_map = {
            'ciudad': 'CIUDAD',
            'ciudad_id': 'CIUDAD_ID',
            'provincia': 'PROVINCIA'
        }
        self._ciudad = ciudad
        self._ciudad_id = ciudad_id
        self._provincia = provincia

    @classmethod
    def from_dict(cls, dikt) -> 'ResponseGetCiudadesCITIES':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ResponseGetCiudades_CITIES of this ResponseGetCiudadesCITIES.  # noqa: E501
        :rtype: ResponseGetCiudadesCITIES
        """
        return util.deserialize_model(dikt, cls)

    @property
    def ciudad(self) -> str:
        """Gets the ciudad of this ResponseGetCiudadesCITIES.


        :return: The ciudad of this ResponseGetCiudadesCITIES.
        :rtype: str
        """
        return self._ciudad

    @ciudad.setter
    def ciudad(self, ciudad: str):
        """Sets the ciudad of this ResponseGetCiudadesCITIES.


        :param ciudad: The ciudad of this ResponseGetCiudadesCITIES.
        :type ciudad: str
        """

        self._ciudad = ciudad

    @property
    def ciudad_id(self) -> int:
        """Gets the ciudad_id of this ResponseGetCiudadesCITIES.


        :return: The ciudad_id of this ResponseGetCiudadesCITIES.
        :rtype: int
        """
        return self._ciudad_id

    @ciudad_id.setter
    def ciudad_id(self, ciudad_id: int):
        """Sets the ciudad_id of this ResponseGetCiudadesCITIES.


        :param ciudad_id: The ciudad_id of this ResponseGetCiudadesCITIES.
        :type ciudad_id: int
        """

        self._ciudad_id = ciudad_id

    @property
    def provincia(self) -> str:
        """Gets the provincia of this ResponseGetCiudadesCITIES.


        :return: The provincia of this ResponseGetCiudadesCITIES.
        :rtype: str
        """
        return self._provincia

    @provincia.setter
    def provincia(self, provincia: str):
        """Sets the provincia of this ResponseGetCiudadesCITIES.


        :param provincia: The provincia of this ResponseGetCiudadesCITIES.
        :type provincia: str
        """

        self._provincia = provincia
